### PR TITLE
Offline support added

### LINKED ISSUE #217: [WIP] Offline support for Editor
### Idea
No service workers are configured at the moment for offline functionality.

### What's your PublicLab.org username?
rexagod

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by rexagod**
Fixes #217 

peek 2019-01-13 11-13

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by rexagod** [comment]
@publiclab/reviewers

**Comment by rexagod** [comment]
@jywarren I'm getting all kinds of errors from the MapModule now. The Editor is running offline, but the map module isn't working, neither offline nor online.

screenshot from 2019-01-30 08-03-48

**Comment by sagarpreet-chadha** [comment]
@rexagod ...it seems you have deleted the comment ? Are the errors are resolved now ? 

I guess the errors were most probably due to low internet connectivity ?
 If the errors still persist , i would be happy to help 😄 .  Thank you :) !

**Comment by rexagod** [comment]
@sagarpreet-chadha Sorry the network here has been very unstable from this morning it seems. Last time I saw my comment was posted, but I may have been disconnected somehow during that. Posting it again.

**Comment by rexagod** [comment]
@jywarren I checked out this branch this morning to find out that I'm getting all kinds of errors from the MapModule now. The Editor is running offline, but the map module isn't working, neither offline nor online. @sagarpreet-chadha Any tips to avoid this will be much appreciated! Thanks!

screenshot from 2019-01-30 08-03-48

**Comment by rexagod** [comment]
Also thank you @sagarpreet-chadha for the quick response and support. Appreciate it. :+1:

**Comment by rexagod** [comment]
Also, I've verified this on high speed net right just now, the errors seem to persist. Looking into this. What do you think @sagarpreet-chadha?

**Pull request closed without merging**
