### PR TITLE
iframe embeds; megamark, domador, insane configs

### LINKED ISSUE #100: YouTube embedding
The rich editor doesn't handle YouTube embeds. (as reported by @Fastie [here](https://publiclab.org/questions/MadTinker/07-30-2017/just-tried-to-publish-a-replication-of-the-knowflow-and-fail)

I believe we could either have an "embeds" button but we'd also have to confirm that embeds don't get scrubbed out as a 'disallowed' content type. We can probably write a test for this if we like, here:

Maybe here: https://github.com/publiclab/PublicLab.Editor/blob/master/spec/javascripts/rich_text_module_spec.js

### PR DESCRIPTION
**Pull request by jywarren**
resolves #100, but not yet complete

### CODE REVIEW

**Comment by jywarren** [comment]
@zengirl2 @Fastie  - i believe this adds YouTube and other embeds that use `<iframe>`, although not all embeds use that technique. But it'll get us YouTube and probably most others.

**Comment by Zengirl2** [comment]
Ooh, that's cool. Youtube embeds could be useful for all sorts of notes.

**Comment by jywarren** [comment]
Oops sorry, i got this issue mixed up with the other one -- file attachments -- which was solved in https://github.com/publiclab/plots2/issues/1561 and which you brought up. But both are now solved!

@Fastie I believe did request YouTube embedding, although I can't find that issue either. But now it works. Whew.

**Comment by Zengirl2** [comment]
@jywarren I just thought you added me since you know I'm a blogger that loves embedding videos LOL.

**Comment by jywarren** [comment]
:-)

**Comment by Fastie** [comment]
I think the YouTube embed issue came up recently when I whined that you couldn't do it if you were using the new rich editor. If that's what this fixes, that's a very good thing. It was confusing, but I embedded a video in the first research note I posted in 2012: https://publiclab.org/notes/cfastie/2-22-2012/dual-camera-kap-rig

**Comment by jywarren** [comment]
This makes it so iframes are not scrubbed out when you switch back and
forth between markdown and rich text editing.

We could also add a button to make it simpler to paste in YouTube embeds
from the rich text mode, since with this change it's now possible, but only
in markdown mode.

**Pull request merged**
