### PR TITLE
Adjust position of wk-commands respective to viewport

### LINKED ISSUE #124: Reposition the bar of editing icons at top of composition box
(reposting on behalf of @ebarry from https://github.com/publiclab/plots2/issues/2334)

### Please describe the problem (or idea)

> What problem could this idea solve?

I would like to consider moving the "kitchen sink" bar of editing icons above the text box, currently it is below the text box. 

screen shot 2018-02-15 at 12 03 39 pm

I feel there are downsides to having the editing icons below the textbox, namely, that doesn't handle well while scrolling up and down the page, and in cases where the note is long, it's hard to scroll all the way down instead of having it pinned at the top. 

The scrolling issue may also be a related but separate issue, in that the /post and /question page should not be "below the fold" on the average desktop display. These pages should not scroll unless someone drags the composition box to be longer. Let me know if i should break this issue out.  

> What did you expect to see that you didn't?

I would expect to see the editing icons positioned at the top of the text box.

### Please show us where to look

https://publiclab.org/questions
https://publiclab.org/post

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

liz

### PR DESCRIPTION
**Pull request by rexagod**
Fixes #124 (and #127)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by rexagod** [comment]
Depending on viewport's postition, `wk-commands` will readjust itself to `document.getElementsByClassName('ple-footer')[0].getBoundingClientRect().height` above the bottom the screen, that is, just above the footer (to prevent overlaping) whenever the viewport's frame goes out of `wk-commands`'s initial position

screenshot from 2019-01-04 07-39-13

**Comment by rexagod** [comment]
@publiclab/reviewers

**Comment by jywarren** [comment]
Oh wow looks great! Would you mind sharing a gif? Thank you!!!

**Comment by rexagod** [comment]
Made some crafty fixes! Here you go.

peek 2019-01-05 07-02

**Comment by jywarren** [comment]
This is fantastic!!!!

**Pull request merged**
