### PR TITLE
PLE v2.1.0 release

### PR DESCRIPTION
**Pull request by shreyaa-sharmaa**
Over a month into GSoc and a month and half into Outreachy, we are ready to release a new version of PLE :heart: 
These are some of the changes introduced:

### Modifications/ Improvements:

1. Remove file button added by @NitinBhasneria in #472
2. UI refinements: Stickiness of toolbar by @Shulammite-Aso in #522 
3. UI refinements: Choose file button UI improved by @NitinBhasneria  in #462 
4. Nodejs version updated to 10 and 12 by @shreyaa-sharmaa in #554 
5. Fix: Disabling of Markdown buttton on using shortcut keys by @keshav234156 in #465 

### Additions:

1. Jest-puppeteer for UI testing by @shreyaa-sharmaa in #532
2. User workflow for documenting bugs by @Shulammite-Aso in #530 
3. Issue template chooser by @Shulammite-Aso in #474 

### Changes for the Users:
1. Remove File Button Added: #472 
Now the image added in the main image module could be removed with just a click.
2. Fix: Disabling of Markdown buttton on using shortcut keys #465 
Earlier pressing CTRL+M disabled the Markdown button. Now, It has been fixed.
3. A better UI with a toolbar that hovers only over the textarea (#522) and improved Choose file button (#462)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
This is great! Are you able to copy in some of the recent changes from https://github.com/publiclab/PublicLab.Editor/pulse that will serve as a kind of release notes, in the description? It can be great to mention peoples' usernames too!

Did you want to incorporate https://github.com/publiclab/PublicLab.Editor/pull/554 or shall we just do this? Finally, can you ask for a review from folks once the release notes are there, and we can have consensus to merge and publish?

Great work, everyone!

**Comment by shreyaa-sharmaa** [comment]
@jywarren I'll work on the release notes and I think we can incorporate #554 too but I'm somewhat concerned about the long time the tests took today. Since development process refinement was one of our umbrella goals I want to be assured that the delay in tests wasn't because of something from our end, even though I could not find anything on the same. I'll rebase or restart travis after a few hours to see if it was a temporary issue. What do you all think?
On that note, awesome work team!!

**Comment by jywarren** [comment]
Hey, this will be fun too - shall we incorporate this badge into the README.md?

https://badge.fury.io/for/js/publiclab-editor#

[npm version](https://badge.fury.io/js/publiclab-editor)

**Comment by jywarren** [comment]
@shreyaa-sharmaa yes, that's a great idea! Perhaps I've been running up our rate limit today, so perhaps after 12 hours or so would be good to retry. Then, feel free to ping me on Gitter after it's merged and I can publish on NPM -- after which I'll give you all rights to do so as well. Finally, we can link from the `plots2` pull request that @dependabot should raise within a day, from here, so we can see the connection from this release to the PR over there. Sound good? 🎉

**Comment by shreyaa-sharmaa** [comment]
> @shreyaa-sharmaa yes, that's a great idea! Perhaps I've been running up our rate limit today, so perhaps after 12 hours or so would be good to retry. Then, feel free to ping me on Gitter after it's merged and I can publish on NPM -- after which I'll give you all rights to do so as well. Finally, we can link from the `plots2` pull request that @dependabot should raise within a day, from here, so we can see the connection from this release to the PR over there. Sound good?

Yeah that sounds great but I'm afraid I don't have the merging rights on this one.

**Comment by shreyaa-sharmaa** [comment]
> Hey, this will be fun too - shall we incorporate this badge into the README.md?
> 
> https://badge.fury.io/for/js/publiclab-editor#
> 
> [npm version](https://badge.fury.io/js/publiclab-editor)
> 
> `[npm version](https://badge.fury.io/js/publiclab-editor)`

Looks good to me. I'll commit the same.

**Comment by jywarren** [comment]
Looking great! Perhaps we should have a section specifically for updates that authors (who use the editor) will want to know. Like:

### Changes to Editor usage

* NEW: Feature to decenter text in wysiwyg and markdown mode (and a brief explanation of how)

(the above we haven't finished, but stuff like that, you know?)

**Comment by jywarren** [comment]
OK I can merge once folks have approved!

**Comment by jywarren** [comment]
And just to confirm, i think before we bump the version # of jywarren/woofmark, https://github.com/jywarren/woofmark/pull/2 may not be included in this release, right? `Drag and drop image refinement` Just checking!

Finally, could we use this format:

* FIXED: Drag and drop image refinements by @NitinBhasneria in https://github.com/jywarren/woofmark/pull/2 (for example)

Thank you so much!!! Get excited!!!!

**Comment by shreyaa-sharmaa** [comment]
I have made changes based on what you told. Also the tests passed quickly this time. :rocket:

**Comment by shreyaa-sharmaa** [comment]
Please add whatever I might have missed @Shulammite-Aso @keshav234156 @NitinBhasneria .

**Comment by jywarren** [comment]
Hi @Shulammite-Aso @keshav234156 @NitinBhasneria -- please leave reviews here so that we can publish this ASAP and see all your hard work in publiclab.org! Thank you! 🎉

**Comment by Shulammite-Aso** [comment]
I think this looks good!!

Would this https://github.com/publiclab/PublicLab.Editor/pull/547 also be included in the new release? just got merged two days ago.

**Comment by keshav234156** [comment]
@Shulammite-Aso I think we can include #547

**Comment by jywarren** [comment]
Well, let's aim for a follow-up release! We can do them quite often. I'll publish this in a bit and report back!!!! Thanks all!

**Comment by jywarren** [comment]
If @nitinbhasneria would like to open up v2.1.1, please go ahead, compiling the changes that didn't make it into this one! Thanks!

**Comment by jywarren** [comment]
Having some `npm publish` issues but i made a GitHub release here too: https://github.com/publiclab/PublicLab.Editor/releases/tag/v2.1.0

for starters!

**Comment by jywarren** [comment]
https://github.com/npm/cli/issues/1433 -- working on it.... might need to be in a couple hours, as I have an appointment in a bit, but will chime in here when done!

**Comment by NitinBhasneria** [comment]
opened #557 for `woofmark` changes.

**Comment by jywarren** [comment]
OK, published it! Congrats, folks! Now let's keep an eye out on `plots2` for dependabot, and link that PR to here for continuity!

https://www.npmjs.com/package/publiclab-editor

**Comment by jywarren** [comment]
https://github.com/publiclab/plots2/pulls

**Comment by jywarren** [comment]
OK! I put some notes into https://github.com/publiclab/plots2/pull/8135, where we had at least one system test fail. I think we ought to do 2 things:

1. fix the issues in our `v2.1.1` release, and merge that into `plots2` instead of `v2.1.0` (that's what "patch-level" releases are for! https://docs.npmjs.com/about-semantic-versioning)
2. add a test to the Editor project that confirms that these behavior (which `plots2` expects in the tests I've highlighted in that PR) in order to codify those expectations in our own tests here. That will prevent us from breaking those assumptions in the future!

Great work, folks; let's move on to the next release quickly with just some minimal bugfixes and then we can plan a `v2.2.0` release with some more features after that. Thanks! 🙌

**Comment by jywarren** [comment]
Hey all - just wanted to celebrate your hard work and put out a tweet about it: https://twitter.com/jywarren/status/1282064048142647298

Please ping me with your twitter handles if you'd like to be mentioned in that thread, i wasn't sure of anyone's but @Shulammite-Aso but want to be sure to appreciate you all! 🎉🎉🎉

**Comment by jywarren** [comment]
And noting next release at https://github.com/publiclab/PublicLab.Editor/pull/557

**Pull request merged**
