### PR TITLE
Padding added to table popover button for editor fixes#752

### PR DESCRIPTION
**Pull request by RaviAnand111**
PR #768 

Hey @TildaDares @NARUDESIGNS , I created this new PR, Can you review it for me please, I know, I am making so many mistakes, Sorry, I get confused sometimes, 
ThankYou for helping me all the time

### CODE REVIEW

**Comment by RaviAnand111** [comment]
Should I close the previous PR #768 ?

**Comment by TildaDares** [comment]
@RaviAnand111 Yes you can close the other PR. Thanks!

**Comment by TildaDares** [comment]
@RaviAnand111 It was the same when I first started contributing so you don't have to worry about making mistakes, we're here to help you.

**Comment by RaviAnand111** [comment]
ThankYou ❤️ 🔥 🎉

**Comment by NARUDESIGNS** [comment]
> @RaviAnand111 It was the same when I first started contributing so you don't have to worry about making mistakes, we're here to help you.

Yea, me too and @TildaDares was (and still is) able to guide me through some of the problems. That's the thing about open source, you get support and you get to learn too.

**Comment by TildaDares** [comment]
@RaviAnand111 Can you add a screenshot of the UI changes? Thanks!

**Comment by RaviAnand111** [comment]
Here you go, 
closer look
image

broader look 
image

**Comment by TildaDares** [comment]
I'll leave the review for @NARUDESIGNS since this issue is a part of his project. 

Great job @RaviAnand111!

**Comment by RaviAnand111** [comment]
ThankYou @TildaDares  🎉 ❤️

**Comment by NARUDESIGNS** [comment]
@RaviAnand111 Looks great!
Good job sir!
cc @TildaDares

**Review by NARUDESIGNS — APPROVED** [review]

**Pull request closed without merging**
