### PR TITLE
PL.Editor #126 Add AutoCenter ability for images and text

### LINKED ISSUE #126: Add ability to center text and photos in rich text editor
a boy can dream!

it would be especially helpful when adding credit to photos so that it isn't easily confusable with the body text.

### PR DESCRIPTION
**Pull request by rexagod**
Fixes #126 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by rexagod** [comment]
@publiclab/reviewers

**Comment by jywarren** [comment]
Wow, this is amazing! Would you mind naming each of your PRs with a short descriptive title so we can easily identify the feature/fix each addresses in list view? This will help us speed up reviewing and help with good documentation in the future. Thank you!!!

**Comment by jywarren** [comment]
Also, whoa!!!! This is really cool. Is there some documentation on how to use it, perhaps? Even just a quick screenshot here would be amazing.

**Comment by rexagod** [comment]
Sure! I'll do that right away.

**Comment by rexagod** [comment]
The screencast pretty much explains the implementation itself but let me know if there's any doubt whatsoever.

autocenter

**Comment by rexagod** [comment]
@shapironick

**Comment by jywarren** [comment]
OK wow! I do wonder - now we will have to ensure our Markdown parser on plots2 also can interpret the `->center<-` syntax:

https://github.com/publiclab/plots2/issues/3889

Does Redcarpet do this? Or could it be configured to?

**Comment by jywarren** [comment]
And just once again, this is really amazing work!

**Comment by rexagod** [comment]
I'll check [this](publiclab/plots2#3889) out @jywarren! In editor's case the parser didn't seem to recognize the arrow tags so I had to configure them manually, explicitly adding support to woofmark for that. Even if RedCarpet does not parse these tags out-of-the-box, adding this enhancement shouldn't be a problem.

Also can we merge this (and #162) now? Thanks!

**Comment by jywarren** [comment]
I think we can merge this, but just to check - they'll remain appearing as
->word<- until we configure RedCarpet, but we shouldn't have trouble if
this gets deployed to plots2 before the corresponding changes are made,
right?

Also, would you mind opening such an issue on plots2 and linking it here?
Thank you, then we can merge!

**Comment by rexagod** [comment]
Can we merge #162 as well?

**Comment by rexagod** [comment]
Can we merge this?

**Comment by jywarren** [comment]
Can you rebase it? Then yep! Thanks!!

**Comment by rexagod** [comment]
Sorry about that.

**Comment by jywarren** [comment]
No prob! Hopefully we have a resolution for that too soon. Thanks for all your help!!!

**Pull request merged**
