### PR TITLE
Fixes Disabling of Markdown buttton on using shortcut keys

### LINKED ISSUE #427: Disabling of #Markdown button
Switching to Markdown mode with ctrl+M disables the #Markdown button and text of the button is not changing to Rich.

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #427

Untitled_ Apr 11 2020 2_03 PM

before changes pressing CTRL + M disabled the Markdown button. Now, It has been fixed.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
The extra spelling changes were also included as in PR #426 changes were directly made to dist files and these spelling mistakes were in node modules.

**Comment by keshav234156** [comment]
@jywarren @VladimirMikulic Please review the changes

**Comment by keshav234156** [comment]
@jywarren @emilyashley  Can you merge this!!

**Comment by jywarren** [comment]
Oh this makes a ton of sense. Thanks a lot!

**Comment by jywarren** [comment]
I just synced the branch so this should be good to merge once it passes. I'll check back in!

**Comment by jywarren** [comment]
This is so odd. I'll close and reopen to try to retrigger the tests. If this happens again, try that too!

**Comment by jywarren** [comment]
And if it keeps happening, it might need a clean rebase... just an idea!

**Comment by jywarren** [comment]
Aha! Done!!! 🎉

**Pull request merged**
