### PR TITLE
Changes font in section 3 (fto-candidate for evaluation)

### LINKED ISSUE #241: Change font to Arial in section 3
### Please describe the problem (or idea)

To make a better looking and coherent format for the editor, I suggest changing the font of these lines to Arial:
issue

### Investigation
It is possible to solve it by just using a surrounding "font" tag like in `<font face="Arial">Your text here.</font>`. @jywarren if you agree, I'll turn this into a FTO issue. Thanks!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

### PR DESCRIPTION
**Pull request by IgorWilbert**
Fixes #241 

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] PR body includes `fixes #0000`-style reference to original issue #
* [X] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by IgorWilbert** [comment]
@rexagod it turns out the font was different because a `h4` tag was being used. I thought it would be cleaner to give a class to the tag and adjust font size in the CSS file. The font-family already is the one you said. It still seems easy enough for a FTO. Please ignore changes in `dist/PublicLab.Editor.js`, I don't know why it keeps making changes everytime I run `grunt build`.

**Comment by rexagod** [comment]
Hey @IgorWilbert! Sorry for the delay. Sure, please go ahead with the fto drafting. Don't worry about the `dist/` changes, but be sure to build before you commit, so as to avoid merge conflicts.

**Comment by gauravano** [comment]
@IgorWilbert can you please copy the screenshot with new font here? Thanks!

**Comment by IgorWilbert** [comment]
capturar
Sure, here it is. Sorry for taking long.

**Comment by IgorWilbert** [comment]
Thanks @gauravano ! However, I've a doubt. Is there a snippet or model to create a FTO Issue? I tried to copy and paste the description of other FTO but the links, of course, didn't come along. I tried to access https://github.com/publiclab/plots2/blob/master/.github/first-timers-issue-template.md but the result is "page not found".

**Comment by rexagod** [comment]
https://github.com/publiclab/PublicLab.Editor/blob/master/.github/first-timers-issue-template.md

**Comment by gauravano** [comment]
Also, the link for plots2 is - https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/first-timers-issue-template.md

Thanks!

**Pull request closed without merging**
