### PR TITLE
Revert "[Security] Bump jquery from 3.4.1 to 3.5.0"

### PR DESCRIPTION
**Pull request by keshav234156**
Reverts publiclab/PublicLab.Editor#468

### CODE REVIEW

**Comment by jywarren** [comment]
@keshav234156 sez:

> @jywarren Due to this PR there were TypeError in test logs. Though test passed. Made a reverted PR #520

Just checking - is this a breaking change in jquery? Because dependabot will try to re-open this... is there another workaround? Thank you!

**Comment by keshav234156** [comment]
@jywarren This version is completely breaking the jquery. I just checked it locally now that they have fixed this in version 3.5.1. Also available here https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/ . Should we fix it manually or dependabot will open it soon?

**Comment by jywarren** [comment]
Ah, i see! Sorry, i totally missed the announcement about the 3.5.0 vs 3.5.1! Can u ping this in the chatroom so folks are aware? What a big reversion...

I don't know if @dependabot knows how to skip withdrawn versions... i think perhaps we could close this and @dependabot would try to open 3.5.1 but i'm not sure. If it doesn't, let's do it manually? Thank you!

**Comment by jywarren** [comment]
Oh aha! Here! I'll just merge this then: https://github.com/publiclab/PublicLab.Editor/pull/513

**Pull request closed without merging**
