### PR TITLE
Fixes for Bold and Italic Test

### PR DESCRIPTION
**Pull request by shreyaa-sharmaa**
This PR adds a condition in the tests to ensure that the first test is conducted in WYSIWYG mode.
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by shreyaa-sharmaa** [comment]
Keshav was facing some trouble with the bold tests failing in two of his recent PRs and the only reason I could think of was that the tests opened up in md mode. So when the bold button is clicked in the first test the text would be added in the `.textarea` and not in the `.wk-wysiwyg` so when compared it couldn't find the string there. And in the next test, it couldn't find the md button which could happen if the md mode is enabled as the md button would be disabled. So I tried adding it as a safeguard to ensure that tests are run in wysiwyg first. When I tested the same in his PR the second test passed but the first one still failed. Since we haven't faced any issue with the first test in other PRs and it seems logically correct I couldn't pinpoint what the reason for it failing could be but opened a PR for it so that this issue could be addressed properly.
The PR where test failed: #561 
SS of the test result:
Screenshot from 2020-07-16 01-40-14

**Comment by shreyaa-sharmaa** [comment]
But my concern is that the first test still failed, and I have reversed all the changes I make in both tests so that they don't interfere with the next test that would be defined. It worked fine for italic but not for bold. There was no reason for the editor to switch from one mode to the other if it's in wysiwyg mode at the start and end of italic test. I feel like this might not be the problem here.

**Comment by keshav234156** [comment]
Let's keep this on hold. Because I am not facing any issue on the main branch now it only with Bootstrap4

**Comment by keshav234156** [comment]
Ok, the main cause of the problem seems to runInBand nature of Travis. locally it can be simulated by 
```node ./node_modules/.bin/jest --runInBand``` you would get the same error as with other PR. Need to find fix for that.

**Comment by keshav234156** [comment]
@shreyaa-s have you been able to find any fix for this?

**Comment by shreyaa-sharmaa** [comment]
Screenshot from 2020-07-21 16-03-41
Have a look @keshav234156. The tests are passing locally now with this command, but I'm not sure what caused it. Should I try committing this?

**Comment by shreyaa-sharmaa** [comment]
Running `npm install` before running the test gets it to work fine. But that doesn't work on PRs. Can we make any change to the travis.yml to fix this? Please test and confirm.

**Comment by jywarren** [comment]
Is it possible we need to tweak dependency versions in package.json? That about `npm install` is a bit mysterious! 😕

**Comment by shreyaa-sharmaa** [comment]
`npm install` made minute changes to the package-lock.json and even that trick has stopped working now for some reason. I tried committing the result but it didn't work as I mentioned. I looked at articles and docs on running Travis tests parallelly but it was more oriented on running integration and unit tests parallelly rather than running every test parallel and we might be able to add it (which is more of a workaround to the problem than an actual fix) but there is not a specific test that we can run separately and the rest will work fine together.  After running it locally a few times you'll observe that there is no fixed pattern to which test would fail or how many. And specifying a different environment for each test would not be a good practice. I'll keep looking into it.

**Comment by keshav234156** [comment]
@shreyaa-s can we close this now? We have fixed this in #566.

**Comment by shreyaa-sharmaa** [comment]
Yeah closing this.

**Pull request closed without merging**
