### PR TITLE
fixes stickness of toolbar

### LINKED ISSUE #394: Stickness of toolbar
Screenshot from 2020-02-01 20-17-37

Screenshot from 2020-02-01 20-36-03

As you can see the toolbar always remains sticked to the bottom. Is it a bug or intended behavior.
It's caused by this piece of code 
https://github.com/publiclab/PublicLab.Editor/blob/7aacb32e7bdb5e3aa72e3ba61311a7fbc442b759/src/modules/PublicLab.RichTextModule.js#L311-L335

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #394 

demo 
https://drive.google.com/file/d/1fMeg_Sn3SPBvrd6oxh3bh7hWXbE203GT/view

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@emilyashley @VladimirMikulic Please review!!

**Comment by keshav234156** [comment]
@emilyashley Can You please merge this!!

**Comment by imajit** [comment]
I think the toolbar is kept floating to help user change and edit text easily . 
Screenshot from 2020-03-02 23-04-46
If the text in text area becomes large then the box automatically adjusts its size to fit the text instead of adding a scroll bar so if we fix the toolbar to the bottom then it becomes difficult to edit . So instead of fixing the toolbar to the bottom we can change visibility so that it only floats in the required area. What are your views on this @VladimirMikulic @keshav234156

**Comment by VladimirMikulic** [comment]
@imajit in my opinion sticky toolbar is unnecessary. If a user's cursor is not visible in the viewport, there is no need to keep the toolbar visible.

**Comment by jywarren** [comment]
Hi, I believe we've now got this resolved in https://github.com/publiclab/PublicLab.Editor/pull/522 -- but thank you!!!!

**Pull request closed without merging**
