### PR TITLE
Fixed nested <a> tags in wk-commands buttons.

### PR DESCRIPTION
**Pull request by manansingh96**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by manansingh96** [comment]
@jywarren In my previous PR #301 , I made some changes, but there were nested <a> tags which were bugging me. I removed the outer <a> tags as they were not necessary.

**Comment by jywarren** [comment]
Ah, ok! And the `autocenter` change is OK too? Can you upload a screenshot to confirm? thank you!!!

**Comment by manansingh96** [comment]
@jywarren Sorry, I was busy so I wasn't able to check here soon. I have attached the screenshot.
screenshot 2019-03-07 at 10 14 01 pm

**Comment by jywarren** [comment]
Great - this is all ready then? If so, i'll merge it -- thank you!

**Comment by manansingh96** [comment]
@jywarren You can merge it. I thought I did reply. Sorry.

**Comment by rexagod** [comment]
Merging this now! Nice work @manansingh96! :+1:

**Pull request merged**
