### PR TITLE
Added eslint,lint-staged and Husky

### PR DESCRIPTION
**Pull request by keshav234156**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@jywarren @Shulammite-Aso @NitinBhasneria @shreyaa-s Can you please help me here. Test are failing
```
Publish button is enabled
     ReferenceError: Can't find variable: PL in file:///home/keshav/PublicLab.Editor/spec/javascripts/button_spec.js (line 7) (1)
     Expected false to be true. (2)
 Editor
   X exists, and has a textarea
     ReferenceError: Can't find variable: PL in file:///home/keshav/PublicLab.Editor/spec/javascripts/editor_spec.js (line 7) (1)
     Expected undefined not to be undefined. (2)
     TypeError: undefined is not an object (evaluating 'editor.options') in file:///home/keshav/PublicLab.Editor/spec/javascripts/editor_spec.js (line 16) (3)

```
ALthough #519 and this PR are same except merge conflict.

**Comment by keshav234156** [comment]
Everything is working fine on PublicLab.Editor/examples/index.html but tests are failing

**Comment by jywarren** [comment]
Oh, looks like it passed now! I'm going to restart it to get Travis-ci.com to run it instead of Travis-ci.org, as I'm doing a migration of our service now. Thanks!

**Comment by keshav234156** [comment]
No not related to migration. It's also failing locally

**Pull request closed without merging**
