### PR TITLE
Filename Error removed

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes: #455

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

editor2

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @jywarren Have a look. 
Thanks

**Comment by NitinBhasneria** [comment]
@emilyashley please have a look.

**Comment by NitinBhasneria** [comment]
@jywarren pls have a look and merge so that choose file button improvement can be tested. thanks

**Comment by NitinBhasneria** [comment]
@VladimirMikulic please review this.

**Comment by cesswairimu** [comment]
Hi @NitinBhasneria this looks good :tada: are you able to plug this to your local plots2 and record a gif of how that will look like?...If not ping me and I will pull your branch and record it on my end. Thanks

**Comment by NitinBhasneria** [comment]
@cesswairimu just noticed I have added the required changes in #462. Please review that.
Closing this.

**Comment by cesswairimu** [comment]
cool thanks

**Pull request closed without merging**
