### PR TITLE
Add suggested tag to tag input on click

### LINKED ISSUE #154: Clicking suggested tag names should enter them into the tag input
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** on click water-quality in recent tag section should take you to /tag/water-quality in new tab

issue

Code's link https://github.com/publiclab/plots2/blob/136b448931f49d8c0baa8bbf79936bcf00e94ad7/app/views/editor/wikiRich.html.erb#L95

After click on water-quality it should take you to(https://publiclab.org/tag/water-quality) in **new tab** :- 
water

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
fixes #154 
A user can now click on a suggested tag name to add the tag to tag input field: 
Screenshot from 2020-04-03 12-54-38

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
also, i think an issue with using tokenfield to add tags is that the placeholder won't go away. I'm thinking of how this could be changed.  Can the placeholder be removed? since we have the helper text?

@VladimirMikulic @gauravano your imput too please

**Comment by Shulammite-Aso** [comment]
On a second thought changing "Recent tags:" to "Click to add recent tags:" could be made a First-time-only issue here on Publiclab.Editor.  
Does this sound okay? 🤷

**Comment by Shulammite-Aso** [comment]
@jywarren @VladimirMikulic @gauravano @cesswairimu kindly review please

**Comment by jywarren** [comment]
> On a second thought changing "Recent tags:" to "Click to add recent tags:" could be made a First-time-only issue here on Publiclab.Editor.

this sounds great!

**Comment by jywarren** [comment]
Thanks a ton!!! 🎉

**Comment by jywarren** [comment]
🎉

**Comment by Shulammite-Aso** [comment]
> > On a second thought changing "Recent tags:" to "Click to add recent tags:" could be made a First-time-only issue here on Publiclab.Editor.
> 
> this sounds great!

😃🎉🎉🎉
I'm now trying to create this first-time-only issue, but I don't know how to. In plots2 you get the option to  make your issue a first-time-only issue once you start creating your issue.  But it's not the same here. 
So I'm wondering if I should copy and paste the issue template from plots2 then add the label or there's a way I can reach the same template here?

**Pull request merged**
