### PR TITLE
Hiding Table popover on pressing `esc` button

### LINKED ISSUE #819: Hide Popover on pressing `ESC` button
The popover can be hidden on pressing `esc` button, this feature is not there right now so this feature can be added for better UI.

### PR DESCRIPTION
**Pull request by RaviAnand111**
fixes #819 
On pressing `esc` button the table popover is disappearing.

### CODE REVIEW

**Comment by RaviAnand111** [comment]
Hey @NARUDESIGNS can you take a look please 
Thanks

**Comment by RaviAnand111** [comment]
I added the function inside the `click` function, but I had this doubt 
```
 if (popoverIsOpen && e.key == "Escape") {
        $(".woofmark-command-table").click();
      }
```
should I add `===` instead of `==` to check the type too ?
@NARUDESIGNS @TildaDares

**Comment by RaviAnand111** [comment]
https://user-images.githubusercontent.com/59113935/152306021-9e185821-2bbe-4cab-a694-d15da45e5ec7.mp4

you can check, how is it working
Thanks

**Comment by RaviAnand111** [comment]
There is one problem, on pressing `esc` key the popover is disappearing but the tooltip is still active/visible so to make it also inactive should I create a new PR or handle it in this PR itself.

Can you please help ?
@NARUDESIGNS @TildaDares 
Thank You

**Comment by NARUDESIGNS** [comment]
> I added the function inside the `click` function, but I had this doubt
> 
> ```
>  if (popoverIsOpen && e.key == "Escape") {
>         $(".woofmark-command-table").click();
>       }
> ```
> 
> should I add `===` instead of `==` to check the type too ? @NARUDESIGNS @TildaDares

This is okay, the event key is coming from javascript which will always be the same so using strict comparison or not is OK.
Well done brother.

**Comment by NARUDESIGNS** [comment]
> There is one problem, on pressing `esc` key the popover is disappearing but the tooltip is still active/visible so to make it also inactive should I create a new PR or handle it in this PR itself.
> 
> Can you please help ? @NARUDESIGNS @TildaDares Thank You

Though it isn't really a problem to be concerned about, I see why it happens.
Normally, on the [Public Lab Editor](https://publiclab.org/post), if you click on the toggle on the tool buttons, you'd see that the tooltip also remains just like you witnessed. This is because the click has no control over the tooltip, so until you click on another element (like a blank space on the page), the tooltip will remain visible. 
@RaviAnand111 
I don't think it's something to be worried about tho.

**Comment by NARUDESIGNS** [comment]
@TildaDares What do you think?
This was part of the feature in my task and the idea was to help keyboard users work with the editor thereby enhancing accessibility/usability.

**Comment by TildaDares** [comment]
I agree with @NARUDESIGNS about ignoring the tooltip. Great work @RaviAnand111!

**Review by TildaDares — APPROVED** [review]

**Comment by jywarren** [comment]
Woohoo! Nice work everyone!!! This could be part of v3.1.1, maybe?

**Pull request merged**
