### PR TITLE
Make MapModule toggleable

### LINKED ISSUE #268: remove requirement of BlurredLocation library if we're not using the Map Module
It looks like the new Map module requires Leaflet.BlurredLocation, as here:

https://github.com/publiclab/plots2/blob/7c1ef45e307a0771a5cbd805b7c6947034bb061b/app/views/editor/questionRich.html.erb#L8-L12

I had to add it there even though we don't use that module in the question form, so I was wondering if we could adjust the code to not require it unless the module is actually used. @sagarpreet-chadha and @rexagod maybe you could help me out? Then we could revert the change I just made to the question form code, and it'd be a bit tidier!

For reference, see the error we got in https://github.com/publiclab/plots2/issues/4742 when we didn't include the dependencies in the HTML page. 

Thanks, all! 👍

### PR DESCRIPTION
**Pull request by rexagod**
Fixes #268

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by sagarpreet-chadha** [comment]
Good Catch @rexagod !

Yes it should do the trick but i think it would be more appropriate to provide in the `options` object the information that we donot want the MapModule (or infact any other module) . Makes sense ?

So i guess by default if we are not providing anything in `options` object , implies we want all the modules . 
Else we have to give `Editor.options.mapModule === false`  in **index.html**  .

So i guess we can update the **Readme**  giving details of how not to add a module . Thanks 😄 !

**Comment by rexagod** [comment]
No problem, @sagarpreet-chadha we can do that too! But shouldn't the code inspiration here be that the user can straight away specify only the options they require rather than knowing all the available options beforehand and specifing the opposite?

**Comment by sagarpreet-chadha** [comment]
Okay so you mean make these lines compulsory ? 
Editor.options.mapModule === true
Editor.options.mapModule === true

**Comment by sagarpreet-chadha** [comment]
Okay so you mean make these lines compulsory ? 
```
Editor.options.mapModule === true
Editor.options.imageModule === true 
Editor.options.titleModule === true 
and so on .. 
```

I guess we can do either ways , but i still prefer to make by **default** all the **Modules to be TRUE** and explicitly give the modules we do not want (i guess we have to write less code in this way) .

Lets wait for @jywarren , @gauravano . Thank You 😄 !

**Comment by jywarren** [comment]
Ah, i see - yes, i think if we started from zero, @rexagod is right that we should be specifying in the positive which modules to use. But now that we are where we are, we'd have to break the API to do so. 

How about this -- we assume all current modules except the MapModule are "default modules" -- and we make them default true and document in README with something like:

```js
var editor = new PL.Editor({ 
  textarea: document.getElementById('my-textarea'),
  destination:        "/notes/create",   // content will Submit to this URL upon clicking "Publish"
  titleModule: true, // default on
  mainImageModule: true, // default on
  richTextModule: true, // default on; can also enable by specifying options with `{ formats: ['csv', 'pdf'] }`
  tagsModule: true, // default on
  mapModule: false // default value
});
```

This way it'll be clear in the setup docs which are default on and how to enable/disable them. What do you think?

**Comment by jywarren** [comment]
Fantastic!

**Comment by rexagod** [comment]
@jywarren Can we merge this? Thanks!

**Pull request merged**
