### PR TITLE
Added eslint,lint-staged and Husky

### LINKED ISSUE #502: Adding a linting tool
Eslint and Husky: 
Eslint is a tool for identifying and reporting patterns faced in ECMAScript/JavaScript Code,with the goal of making the code more consistent. In order to force the contributor to use Eslint before they commit their code we will use Husky

Eslint and Husky where previously used in Image-Sequencer project. We can think of other alternative tools if it doesn't work here.

### PR DESCRIPTION
**Pull request by keshav234156**
Fixes #502 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@VladimirMikulic I believe you once suggested to have a linter for this project, can't recall where? So here it is. There were so many linting errors, still fixing it

**Comment by keshav234156** [comment]
@jywarren @emilyashley @Shulammite-Aso @shreyaa-s @NitinBhasneria please review!!

**Comment by jywarren** [comment]
Hi! This looks great. Will it add any extra steps we need to warn other devs of? Things to watch out for? Things we need to mention in the README, maybe? Thank you!!!

**Comment by keshav234156** [comment]
No, we don't need to give any instruction to future devs. npx eslint command will automatically run before every commit.

**Comment by jywarren** [comment]
Hi, that's great. Just a few more Qs:

1. is it run in Travis, and can you link me to the lines in the travis output in this PR that show it?
2. will it block merges if it fails in travis? 
3. if it blocks, how is this shown and explained to people who've opened a PR?

Thank you!!

**Comment by emilyashley** [comment]
Cool, thanks Keshav. I'm a fan of linting -- especially if it's standard across dev environs and repos.

Just curious if this plays nice with Git GUIs (i.e. Github Desktop) or if it requires developers to be using the git CLI.

**Comment by keshav234156** [comment]
@emilyashley it works only with git CLI. I believe mostly use the git CLI for their work. If someone uses the Git GUI then this won't work but whenever next developer who uses the git CLI makes a commit then it would fix linting issues of previous developer as well as we are running eslint through all js files in the repository

**Comment by emilyashley** [comment]
Cool, just noting that the more linting differs between developer environments the more linting changes can make Pull Requests and diffs harder to read. 

But if the community is down with it I am. :+1:

**Comment by govindgoel** [comment]
@keshav234156  Can you resolve the conflicting files.

**Comment by jywarren** [comment]
Hi @keshav234156 - thank you. Just to clarify, will this then be a blocker for folks using non-CLI systems? If not, I think we are OK with it, but we should note that it's optional.

Apart from that i agree with @emilyashley that including linting changes in regular PRs is not ideal for readability reasons. Perhaps this means that we should also open some PRs to lint the entire codebase as a project unto itself, so that PRs don't include linting of entire files every time they're touched? But, open to ideas from either of you! Thanks @govindgoel too!

**Comment by keshav234156** [comment]
@jywarren This will not at all be a blocker for non-CLI systems. Though I believe readibility become better if we have code is proper linted and have a proper indentation. Also, we have already been using it in Image-Sequencer and it works pretty well.
Thanks!!

**Comment by cesswairimu** [comment]
Hi @keshav234156 could you please fix the conflicts ...thanks

**Comment by keshav234156** [comment]
@jywarren @Shulammite-Aso  @shreyaa-s  @NitinBhasneria Can you please help me here? Test are failing after I fixed merge-conflict. It shows

**Comment by jywarren** [comment]
Hi! I'm sorry, there are still some merge conflicts to resolve. Apologies on this as we're getting the next release set up, but we should be able to merge this and move forward if you can resolve these. Thank you!

**Comment by keshav234156** [comment]
@jywarren Doing this right now

**Comment by keshav234156** [comment]
@jywarren Done!!

**Comment by jywarren** [comment]
Great work here. Merged!

**Comment by cesswairimu** [comment]
:tada: :tada:

**Pull request merged**
