### PR TITLE
Version bump to 2.0.0

### PR DESCRIPTION
**Pull request by rexagod**
Fixes https://github.com/publiclab/PublicLab.Editor/pull/278#issuecomment-461103698

@jywarren Please review.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Thanks, you think 2.0 because there's a breaking change? I guess I'm not sure; technically the introduction of MapModule was a breaking change although we didn't know it. Do you think this qualifies to bump to 2.0? Tell me what you think!

**Comment by rexagod** [comment]
@jywarren I think we can acknowledge the fact that the Map module was indeed a breaking change and thus a major update so incrementing the most significant digit made sense. Nonetheless, if we look at this as a minor functionality update along with the `atwho` implementation, and approximately 50 (54 commits since latest github release to be exact) other bug fixes (inclusive of many minor functionalities too, for eg., the `AutoCenter` button, etc.), I believe we'd land somewhere close to the aforementioned version. But it may be probable that I'm off by a few minor versions here, and if you feel so, let me know and I'll make the appropriate changes. Thanks!

**Comment by jywarren** [comment]
OK, let's do 2 things, let's actually release this as 1.x.0, so that downstream users (even if it's just us) get their code fixed even if they're pegged to `^1.0.0`, and then consider a re-release a new 2.0 version. That way we "unbreak" the code and the Map module addition is considered a bug with a bugfix, but we can consider whether we want to do a full increment of the version based on the additions we've made. How does that sound?

**Comment by rexagod** [comment]
Sounds good! I think we can first release it as `1.9.0` and then I'll incorporate the required changes for the `2.0.0` re-release. What do you think?

**Comment by jywarren** [comment]
perfect!

**Comment by jywarren** [comment]
This looks good to go; if you'd like to merge this, go ahead -- let's also bump the versions of this lib in `plots2` and `inline-markdown-editor`!

**Comment by rexagod** [comment]
@jywarren Can you publish this to npm? I'll then make the required changes to both the libs. Thanks!

**Comment by jywarren** [comment]
Done!

**Pull request merged**
