### PR TITLE
Publish bar Improved:

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes: #435
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

publich

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @jywarren @cesswairimu @govindgoel have a look.
Thanks

**Comment by VladimirMikulic** [comment]
Why is it opened by default if the input is not focused?

**Comment by Shulammite-Aso** [comment]
Hi @NitinBhasneria This is the same issue I have worked on in #464 . I didn't know you'll be working on it. 
You and @VladimirMikulic had asked that I work on it.

**Comment by VladimirMikulic** [comment]
@Shulammite-Aso that's right. @NitinBhasneria I'll have to close this since @Shulammite-Aso has been already assigned to #435.

**Comment by Shulammite-Aso** [comment]
Also I think the changes you have made will only be visible to the example page, but not on publiclab.org/post. This is because the classes you have added in example.html will not be seen in plots2, I think.

**Comment by Shulammite-Aso** [comment]
> @Shulammite-Aso that's right. @NitinBhasneria I'll have to close this since @Shulammite-Aso has been already assigned to #435.

Oh, okay. Thank's

**Comment by NitinBhasneria** [comment]
In this case it is okay. no problem.

**Comment by NitinBhasneria** [comment]
> Also I think the changes you have made will only be visible to the example page, but not on publiclab.org/post. This is because the classes you have added in example.html will not be seen in plots2, I think.

This does not depend here. This will be updated with rich.html.erb afterward. Got it? IF you have any doubt please ask. Thanks

**Comment by Shulammite-Aso** [comment]
Oh. I had avoided making changes to index.html in example folder because I thought they're not visible to plots2. The README.md file says that html changes should be made to rich.html.erb. 

Meanwhile I'm not meaning to attack you. I'm sorry if my comment about your changes somehow feels that way. Was never my intention.

**Comment by NitinBhasneria** [comment]
@Shulammite-Aso No, I am not thinking like that.

**Comment by Shulammite-Aso** [comment]
Thank you @NitinBhasneria 

Inbetween, I think we should still get clarification as to whether changes made in the example folder gets reflected on publiclab.org/post, for next time. 

You can tag whoever you want to help and that.

**Comment by NitinBhasneria** [comment]
@Shulammite-Aso 
NO, the changes from the example are not directly reflected in plots2. Further, after the changes made in examples are perfect the changes will be then manually made in plots2/rich.html.erb.
For example, the editor example is the most updated editor we are having now. After a time period, admin will manually add these changes to plosts2. Is it clear?

**Comment by Shulammite-Aso** [comment]
Okay!👍

**Pull request closed without merging**
