### PR TITLE
btn-secondary-outline changed to btn-light, transparent buttons is re…

### LINKED ISSUE #753: Buttons has no background which makes it possible to see text behind it.
When the page is scrolled to a particular threshold, the tool buttons sticks to the page, allowing other contents to scroll under them. However, the tag, table, horizontal line, center and youtube buttons all have no backgrounds which make it possible to see the text which they overlap.
I expect those buttons to have a background and maybe match other button styles like the bold, italics, blockquotes etc...

Here's what it looks like presently

Screenshot 2021-10-24 at 06 18 34

### PR DESCRIPTION
**Pull request by RaviAnand111**
...solved

fixes #753 

The button was transparent now it is not.

### CODE REVIEW

**Comment by RaviAnand111** [comment]
> 

twitter handle - @ravi_anand_dev

**Comment by jywarren** [comment]
Hi @RaviAnand111 thank you for your contribution! @NARUDESIGNS would you mind taking a look at this? Thank you!!

**Comment by NARUDESIGNS** [comment]
> Hi @RaviAnand111 thank you for your contribution! @NARUDESIGNS would you mind taking a look at this? Thank you!!

sure, thanks.

**Comment by NARUDESIGNS** [comment]
> Hi @RaviAnand111 thank you for your contribution! @NARUDESIGNS would you mind taking a look at this? Thank you!!

Sure @jywarren 
@RaviAnand111 I noticed your code formatter (eslint or maybe prettier, I'm not sure which) did some code formatting on so many lines. Can you please undo those changes, disable your code formatter and push again so that this PR only captures the changes required to fix the specified issue?
Thanks, champ!

**Pull request closed without merging**
