### PR TITLE
remade wysiwyg commit to push in a new PR

### PR DESCRIPTION
**Pull request by NARUDESIGNS**
Remade the wysiwyg jest test conversion due to issues from [former PR](https://github.com/publiclab/PublicLab.Editor/pull/785) to see if all tests work fine. 
Finger crossed 🤞

### CODE REVIEW

**Comment by jywarren** [comment]
This is really so strange Paul I'm sorry. Somehow this test is affecting other files and I think we have to figure out why or how that could happen. What if we actually remove all of the content of the tests or even just all of the tests themselves or we test something obvious like true is true. That way I mean if it's a completely obvious test it doesn't seem like there's any way I could affect other test files right? Do you want to give that a try in this pull request?

**Comment by NARUDESIGNS** [comment]
Sure, it's something I can try. Although, I don't know why it's particular to this test. You can see that this PR - #799 was made today and all test passes. But we could try your idea nonetheless.

**Comment by NARUDESIGNS** [comment]
@jywarren I just tried pushing the files with 
```javascript
expect(true).toBe(true);
```
But it still fails. I have another idea. I going to create a new file entirely in a new branch, add this test case and then push to see if it passes. If it does, I'd go on to add a test case and push changes to see again if it passes.
My only concern is that it would mean I've made 3 PRs just trying to debug this issue.

**Comment by NARUDESIGNS** [comment]
solved @ #785

**Pull request closed without merging**
