### PR TITLE
Multiple popups open up at a time 

### LINKED ISSUE #750: Multiple pop-ups at once when tool buttons are clicked.
Screenshot 2021-10-13 at 12 30 05 AM

I clicked on several tool buttons such (e.g table, link etc...) and all corresponding popups occurs. However, they stay on screen until you click again on the icon that triggered the pop-up.

I expect a pop-up to close when I do one of the following:
* click the `esc` button,
* click on the page,
* click on another pop-up (to close previously opened pop-up).

This issue can be replicated on the [publiclab editor](https://publiclab.org/post) by clicking the tool buttons as you see in the image above.

### PR DESCRIPTION
**Pull request by RaviAnand111**
fixes #750 

This is the code I have done, all the improvement I had done till yesterday, I have deleted it this code just has the code I talked about in the issue chats, now we can discuss and find a way to solve this problem. 
Thank You 
@NARUDESIGNS @TildaDares

### CODE REVIEW

**Comment by NARUDESIGNS** [comment]
Or would you prefer me to share with you the code snippet I added so that you can try it on your local environment and then push the changes?
@RaviAnand111

**Comment by RaviAnand111** [comment]
Both are fine @NARUDESIGNS you can share or make a PR whichever sounds good to you, as soon as you push it can we try to find ways to solve this. 
Thanks

**Comment by TildaDares** [comment]
Hi @NARUDESIGNS, to make it easier for @RaviAnand111 to incorporate those changes you can make use of [GitHub suggestions](http://haacked.com/archive/2019/06/03/suggested-changes/#:~:text=When%20you%20hover%20over%20the,button%20to%20add%20a%20suggestion).

**Comment by NARUDESIGNS** [comment]
Thank you @TildaDares but the changes I added are on lines that aren't in his commit, maybe I'd just share as a comment instead.

**Comment by NARUDESIGNS** [comment]
Thank you @TildaDares but his commits didn't include lines where I wanted to indicate the changes. I thought of making a PR cause I don't know if this can explain it enough but let me try this first. 
@RaviAnand111 Please have a look at these snippets and then try to insert them. I've included some codes that were there before so that you can have an idea of where to include these snippets. The file is [PublicLab.RichTextModule.Table.js](https://github.com/publiclab/PublicLab.Editor/blob/main/src/modules/PublicLab.RichTextModule.Table.js)

```diff
+ let popoverIsOpen = false;
  $('.wk-commands .woofmark-command-table').click(function() {
+    popoverIsOpen = !popoverIsOpen;
    $('.ple-table-size').click(function() {
```


```diff
        $('.woofmark-command-table').popover('toggle');
      });
    });

+    // close table popover when user click outside the page
+   $(':not(".woofmark-command-table")').click((e) => {
+      // check to see that the clicked element isn't fa-table icon, else when you click on the fa-table icon, the popover will close
+      if($('.woofmark-command-table').children()[0] != e.target){
+        const popoverContainer = document.querySelector('.popover');
+        const isChildElement = popoverContainer.contains(e.target);
+        if (popoverIsOpen && !e.target.classList.contains("woofmark-command-table") && !isChildElement) {
+          $('.woofmark-command-table').click();
+        }
+      }
+    });
  });
};
```

**Comment by NARUDESIGNS** [comment]
I hope this helps.

**Comment by RaviAnand111** [comment]
Thanks @NARUDESIGNS , I will add them in the code and make a commit here.

**Comment by RaviAnand111** [comment]
Hey @NARUDESIGNS, you have written a very beautifull code, if is working perfectly.

**Comment by NARUDESIGNS** [comment]
Thank you @RaviAnand111 even though I feel like it's many lines of code for a simple task but you get the idea or pattern we can use for the other popovers right?
1. we use a boolean `popoverIsOpen` variable to know whether a not the popover is open.
2. next, we check if there's a click on the page and not the table tool button nor its icon
3. we then check to see if the element being clicked is contained in the popover because we wouldn't want to hide it if, for example, the user clicks on the `-` or `+` button
4. if all checks out, then we just want to call the `click` event on the table button which is capable of hiding the popover.

**Comment by RaviAnand111** [comment]
I got it, @NARUDESIGNS 
 Thanks for your help, I will try to learn as much as I can from you. 
 And now I will add this code in every button in `.wk-commands` and then commit it.
 Thanks again 
 @NARUDESIGNS @TildaDares  for this great opportunity where I am getting alot to learn.

**Comment by NARUDESIGNS** [comment]
Alright. At Public Lab, I learned that a PR should do just one thing (unless there are very minimal changes you want to group together). So I think we should make separate PRs for each tool button that has popovers. You can make changes for this table button and commit it then create another PR for any other tool button you'd like to work on next.

**Comment by RaviAnand111** [comment]
ok great, then I will do it the way you said, and different PRs for different popovers.
Thanks 
@NARUDESIGNS @TildaDares

**Comment by RaviAnand111** [comment]
I just pushed the new changes, you can check and tell me if there is something to change.
So now I have to make a new PR and solve popup problem of other buttons just like this, 
So I will be doing that. 
Thanks 
@NARUDESIGNS

**Comment by RaviAnand111** [comment]
I just had this doubt, @NARUDESIGNS as in the end all the code in modules become part of `PublicLab.Editor.js` so I cannot create same variables again again right, I would have to give different name to every variable in every module. 
right ?

**Comment by NARUDESIGNS** [comment]
The `let` declaration keyword scopes the variable to its enclosing function, therefore the variable isn't global but is only accessible within the function it was declared.
I don't think this will be a problem but when you make your next attempt we can find out.

**Comment by RaviAnand111** [comment]
I tried both ways, with different variable names and with same variable names and I found out that both ways are working perfectly, there is not problem, so what do you recommend which way should I do it ?
Thanks

**Comment by RaviAnand111** [comment]
I am adding the function in try catch as it is printing errors in console on clicking on the page as the contains function is being called on null.

**Comment by NARUDESIGNS** [comment]
Is this for a different tool button and popover?
If yes, I think we should make a PR for it, and then we can move the conversation about it there.

**Comment by RaviAnand111** [comment]
See this is the error in the console, 
image

what I have understood is, 

`+    // close table popover when user click outside the page
+   $(':not(".woofmark-command-table")').click((e) => {
+      // check to see that the clicked element isn't fa-table icon, else when you click on the fa-table icon, the popover will close
+      if($('.woofmark-command-table').children()[0] != e.target){
+        const popoverContainer = document.querySelector('.popover');
+        const isChildElement = popoverContainer.contains(e.target);
+        if (popoverIsOpen && !e.target.classList.contains("woofmark-command-table") && !isChildElement) {
+          $('.woofmark-command-table').click();
+        }
+      }
+    });`

as we are calling `.contains` so it is giving error on being called on `null`

**Comment by RaviAnand111** [comment]
No this error is on the table button as well. @NARUDESIGNS

**Comment by NARUDESIGNS** [comment]
Yea I noticed. I dropped a suggestion for you. Please check.

**Comment by RaviAnand111** [comment]
hey @NARUDESIGNS , sorry to ask, where can I see the suggestion, I can't find any. 
Thanks

**Comment by NARUDESIGNS** [comment]
Yea there are too many comments already so I'd just paste it here:

```if (popoverIsOPen && $('.woofmark-command-table').children()[0] != e.target) {```

**Comment by RaviAnand111** [comment]
I am adding the same video from the other PR, if any more demo video is required, then I will make another video 

https://user-images.githubusercontent.com/59113935/150100929-a2b52576-fce0-4d39-8436-b054d4a94e32.mp4

You can check the demo video 
@NARUDESIGNS @TildaDares @jywarren 
Thanks

**Review by NARUDESIGNS — COMMENTED** [review]
Awesome!

**Comment by NARUDESIGNS** [comment]
Hi, @RaviAnand111 there are 10 commits in this PR and some of the commits are from another PR. This usually happens when you checkout a new branch X from another branch Y, the commits from branch Y are automatically added in new branch X.

Did you checkout this branch from `main` branch?

Screenshot 2022-01-19 at 11 09 22 AM

**Comment by RaviAnand111** [comment]
I think I have made a mistake here, and checkout a new branch from a branch,
What can I do to solve this ? 😨

**Comment by NARUDESIGNS** [comment]
Not to worry, I made same mistake some time when I joined as well. Tilda shared a very helpful resource, have a look at it here - https://luisdalmolin.dev/blog/branched-off-the-wrong-branch-in-git/

**Comment by RaviAnand111** [comment]
hey @NARUDESIGNS I think I have done a massive mistake here.
git-image

Can you tell me how to solve, I am confused right now

**Comment by RaviAnand111** [comment]
My mistakes:
1. I made a PR from `main` branch  #768 #769 
2. then I created a branch `multiple-popups`from `main`, there made a PR too #793
3. then created another branch from `multiple-popups` branch with name `customInsert-Popover-problem` and made a PR from there too. #794 

It seems messed up, what should I do ?

**Comment by TildaDares** [comment]
> Not to worry, I made same mistake some time when I joined as well. Tilda shared a very helpful resource, have a look at it here - https://luisdalmolin.dev/blog/branched-off-the-wrong-branch-in-git/

@RaviAnand111 Have you tried this?

**Comment by RaviAnand111** [comment]
Yeah, I tried this, it is giving merge conflict and something, I think the main mistake I did was, made  a change and PR from `main` branch @TildaDares

**Comment by RaviAnand111** [comment]
I think I should create a new branch, before I created a PR from main and `git rebase` that PR to that branch, what do you guys think ? is there any way to do that `safely` ?
@NARUDESIGNS @TildaDares

**Comment by TildaDares** [comment]
@RaviAnand111 It’s best to leave the main branch untouched and use branches for your work. 

I’m looking for resources to help with your issue.

**Comment by RaviAnand111** [comment]
Yes I learned my lesson from this mistake, thankyou for helping me,

**Comment by TildaDares** [comment]
@RaviAnand111 I found this article about how to rebase. You could pick and drop the commute you want in this PR. https://www.google.com/amp/s/www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request.amp

**Comment by RaviAnand111** [comment]
Hey guys, I tried to solve this so I will write down what steps I took : 
1. I created a branch `feature` at the commit before the commit in which I made a PR from `main`.
2. Then I did `git rebase` from the main commit in which I did a PR and transported all of commits after it in the `feature` branch.
3. Then I did `git reset` to the commit point in which I created `feature` branch. 
3. Then I did a force push `git push -f` to my remote repo.
4. Then I did `git fetch upstream` and `git pull upstream main`


I think I should make a video with sketch and drawing to make you guys understand, if you guys ask for it then I will make one.

so now we are here, now head is at the commit in which I have not pushed a PR yet,  but the PR's I have done already are showing those previous files.

So I am thinking of closing those PR's and creating new one's 
It was alot confusing but I tried to solve it so you guys don't have to waste time on it but I don't know if it was right or wrong
 Its 2:30 AM here, now I am going to sleep, 
If I did any mistake then please share and thankyou for helping

**Comment by NARUDESIGNS** [comment]
Hello @RaviAnand111 
Though your `RaviAnand111:main` branch is now in sync with `publiclab:main`, this PR still contains 10 commits, with the first 2 commits about publiclab#768

Maybe we need to just start the whole process all over since your main branch is now properly synced with that of publiclab. 
So I advise that you 
* check out to main (i.e `git checkout main`)
* create and branch off to a new branch (e.g `git checkout -b "fix-multiple-popover-table-popover")
* make changes and push new branch/changes to remote repo
* create new PR

How about that?
cc @TildaDares

**Comment by RaviAnand111** [comment]
That sounds good @NARUDESIGNS ,
 once @TildaDares confirms that, I will start doing it.

**Comment by RaviAnand111** [comment]
And one more thing, 
should I delete the PR's I have created already ?

**Comment by TildaDares** [comment]
Hi @RaviAnand111, you can follow those steps @NARUDESIGNS outlined. You can also close these PRs when you’ve opened the new ones. Thanks!

**Comment by RaviAnand111** [comment]
Thanks @NARUDESIGNS @TildaDares

**Pull request closed without merging**
