### PR TITLE
Added links in the header.

### PR DESCRIPTION
**Pull request by manansingh96**
Added links to GitHub repo and PublicLab's website in the header.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by manansingh96** [comment]
@publiclab/reviewers @IgorWilbert @rexagod Please review.

**Comment by rexagod** [comment]
@manansingh96 can you send us screenshot of this? Thanks!

**Comment by manansingh96** [comment]
@rexagod 
image

**Comment by rexagod** [comment]
Looks great! Thank you @manansingh96 for your contribution! We'd love to see more of it in the future!! :+1:

**Comment by rexagod** [comment]
Pinging @jywarren just to notify him about this.

**Comment by gauravano** [comment]
hey @manansingh96, nice work. Just a suggestion, adding `Fixes #[issue-number]` closes the issue after PR gets merged, so it's a nice practice.

**Pull request merged**
