### PR TITLE
Crescive issue232 patch: Added fix for unusual overlapping behavior

### LINKED ISSUE #232: Fix tags placeholder overlap
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update**: Currently the tags section's placeholder goes on top of the `wk-prompt` dialog box. Please add the code snippet `z-index: 2;` just after this line `#157` https://github.com/publiclab/PublicLab.Editor/blob/ffcb496c6be2abf813c7e38f8ef3d72a8426251d/dist/PublicLab.Editor.css#L157

zindex

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### PR DESCRIPTION
**Pull request by Crescive**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

Fixes #232 

__Details__: Added the `z-index: 2` at line 158 in the PublicLab.Editor.css file to resolve overlapping behavior described in Issue #232 

@rexagod Thanks for the opportunity! Can you take a look at this PR?

### CODE REVIEW

**Comment by Crescive** [comment]
@geekychaser Done! Is that good?

**Comment by rexagod** [comment]
It's okay. I think we can merge this!

**Comment by Crescive** [comment]
@rexagod @geekychaser Awesome! Thanks, guys!

**Comment by jywarren** [comment]
Great!!!

**Pull request merged**
