### PR TITLE
Added At.js support (removed Horsey and Banksy)

### LINKED ISSUE #225: At.js refactoring and fixes

### PR DESCRIPTION
**Pull request by rexagod**
Fixes #225, #44

atjs_

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by rexagod** [comment]
@jywarren Do we need `webgl-distort`? Also currently there are two repository properties in `bower.json`.

https://github.com/publiclab/PublicLab.Editor/blob/1584378fa079c98209ef34bea2b1688ad82bc6d6/bower.json#L16-L19

https://github.com/publiclab/PublicLab.Editor/blob/1584378fa079c98209ef34bea2b1688ad82bc6d6/bower.json#L5-L8

**Comment by jywarren** [comment]
Whoa certainly don't need webgl-distort, good catch!

I'd be happy to accept a change to the repository properties. Is this one of the libs where we are using Bower still or should we be deprecating it for a pure npm package.json approach?

This is looking great! Do I see a bit of delay in the autosuggestion popping up? I'm guessing it's local and static in the example, any idea why that might be slow?

I'd like to potentially remove the "suggestions" line to keep it simple. Is that ok? 

Thanks!!! Very cool!

**Comment by rexagod** [comment]
Hi @jywarren! Hope you're doing well. I have removed `webgl-distort` from `bower.json`, and the `Suggestions` heading from both "@" callouts and "#" hashtags as well.

I did think of using npm for this, since bower has been [deprecated](https://snyk.io/blog/bower-is-dead), but the [README](https://github.com/ichord/At.js/blob/master/README.md) suggested using `Component` or `Bower` to install `At.js` and the underlying `Caret.js`, maybe because the package isn't maintained anymore. If you're interested, I can try doing a npm implementation for this and verify it on my local in a pure npm approach and let you know.

As for the delay, other than my network being a bit slow at the time of recording this, was due to the large number of users (300k+, as you mentioned [here](https://github.com/publiclab/plots2/issues/3147)) currently in our database which hinders the API response time and also increased the "`@gauravano`" fetch time in the above example (as it occurs on a high speed connection too, and I have doubly checked this). This normally does not happen for hashtags, since the notes are pretty low in number right now, so a GET request gets through pretty fast, but this can be fatal for the response time as the number of notes increase in the near future. The same goes for other resources as well. Please refer to my issue below for a better (visual) explaination, and @milaaraujo's issue that rounds up all the similar issues and resources related to the slow API problem.

**My issue (response difference between @ and #)**: https://github.com/publiclab/plots2/issues/4670
**@milaaraujo's issue**: https://github.com/publiclab/plots2/issues/4561

**Comment by jywarren** [comment]
Ah ok this is great, I didn't realize you were testing against the full
database, but that makes sense and we can approach this through API
optimization.

I did want to ask if you'd come across ideas for timing optimization of
requests - either limiting the rate or starting only after 3 chars are
entered and/or "denounce" strategies... We've recently been trying to
consolidate issues related to this in plots2.

I can probably review the Bower changes later today if I have a chance
(traveling!). I admit I am not remembering what the default is for the
editor library but I'd like to do as we've done with other included libs.
Thanks!

**Comment by jywarren** [comment]
Ok, yes I think we had better use npm here, I'm sorry to say. In general we've been phasing out Bower slowly on all repositories. 

Thanks @rexagod! 

Also I see a lot of small formatting changes like double/single quotation marks. Was that just tidying up? Thanks!

**Comment by rexagod** [comment]
@jywarren Shifted to NPM. Also, the small formatting changes were due to Prettier, it stresses on using the double quotes for some reason.

**Comment by rexagod** [comment]
@jywarren @gauravano Can we merge this now?

**Comment by jywarren** [comment]
Fantastic work @rexagod !!! Shall we bump the version number by a `0.x.0` minor value? Awesome!!!!!! 🎉 🎉 🎉

**Comment by rexagod** [comment]
Thank you @jywarren! I do think we can introduce a minor bump at this point. Thanks again!

**Pull request merged**
