### PR TITLE
Incorporate build in ci

### LINKED ISSUE #196: Make testing cover the build process "grunt build"
This will help address #195 

We need to get our tests to run `grunt test` and pass only if that completes. Then we'll be able to more confidently merge @dependabot updates that address build code such as Browserify in #163.

@rexagod would you have any interest in trying to get this working? I think it'd be an adjustment to the Gruntfile. We'd want to first confirm that a failed build results in Travis reporting a build failure. 

Thanks!!!

### PR DESCRIPTION
**Pull request by rexagod**
Fixes #196 --> https://travis-ci.org/publiclab/PublicLab.Editor/jobs/475590529#

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Oh cool! Can you demonstrate that it breaks the Travis build if grunt build fails? Maybe... by removing one of the npm packages that build depends on? (we can revert the commit once demonstrated, just want to be sure!) 

Thanks so much, this is great!

**Comment by rexagod** [comment]
Sure, although the current travis configuration fails if build does (as is shown [here](https://travis-ci.org/publiclab/PublicLab.Editor/builds/476022827)), I did notice there was a chance to refactor the yml and went with it instead, hence making some the necessary changes.

**Normal run:** https://travis-ci.org/publiclab/PublicLab.Editor/builds/476030956
**Failed run after `grunt-browserify` was removed:** https://travis-ci.org/publiclab/PublicLab.Editor/builds/476031041

**Comment by jywarren** [comment]
> >> Local Npm module "grunt-browserify" not found. Is it installed?


Awesome. Merging this! Would you be interested in adding this to a number of our other JS repositories? These could all use it; we could mention this in the weekly Check-In to recommend others make this change if you don't want to do all yourself?

* https://github.com/publiclab/leaflet-blurred-location/
* https://github.com/publiclab/leaflet-blurred-location-display/
* https://github.com/publiclab/image-sequencer/
* https://github.com/publiclab/Leaflet.DistortableImage
* https://github.com/publiclab/infragram/
* https://github.com/publiclab/spectral-workbench.js/
* https://github.com/publiclab/inline-markdown-editor/

**Comment by rexagod** [comment]
Sure! I'll do it.

**Pull request merged**
