### PR TITLE
Add test for empty bold tags functionality

### PR DESCRIPTION
**Pull request by IgorWilbert**
Related to #202 . I'm almost sure I changed more files than I should have, maybe due to a mistake during the set up. Please let me know if changes are required. Thanks!

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X] code is in uniquely-named feature branch and has no merge conflicts
* [X] PR is descriptively titled
* [X] PR body includes `fixes #0000`-style reference to original issue #
* [X] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by rexagod** [comment]
Haha. No need to worry @IgorWilbert, the diff can be **very**  specific sometimes  and show up any minute changes like carriage returns, etc. That being said, other than your `package.json`, all the files you changed were necessary, since `dist/ and package-lock` buildup normally occurs every pre-commit. Also, there's absolutely no need to be tensed up, after all, we're here to help you in any way we can.

Great work and Cheers!

**Comment by rexagod** [comment]
Hey @IgorWilbert! It's always good to see someone joining us. You see, there have been some changes to the master branch, and therefore, you'll need to get your branch up to speed to the latest changes first before we can merge that. In other words, you'll need to "rebase" it. As the word suggests, this will shift the base of your branch to the updated one in time, on which you can then make these changes on.

The simple (and unsafe) approach here would be to `git pull [this repo link] [your feature branch]` and then make changes **again**.

If you don't want to do so, a safer approach would be to try merging the changes on your current branch with the updated master branch so as to update it for which you'll need to `fetch the changes` and then `merge`. This way git gives you the ability to review the changed commits as well.

This maybe of [help](https://stackoverflow.com/a/7104747).

Thanks!

**Comment by IgorWilbert** [comment]
Hey @rexagod ! I think this is it. Thanks!

**Comment by IgorWilbert** [comment]
@rexagod also, could you please merge it? I had some trouble with my master branch, so it would be easier to fork the repo again rather than fixing it. Thanks

**Comment by jywarren** [comment]
This looks great. Super good job!

**Comment by IgorWilbert** [comment]
Thank you!

**Pull request merged**
