### PR TITLE
Fixed style on dropdown button in custom insert popover

### PR DESCRIPTION
**Pull request by Innominata88**
Regarding first-timers-only issue: 
https://github.com/publiclab/PublicLab.Editor/issues/798

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by TildaDares** [comment]
Hi @Innominata88, you did a great job. You need to run `grunt build` after adding a change.

> Make changes to the files in the /src/ directory, then run grunt build to compile into /dist/PublicLab.Editor.js. This will use grunt-browserify to concatenate and include any node modules named in require() statements.

**Comment by Innominata88** [comment]
@TildaDares Thanks so much for the feedback and I apologize for the delay. I was able to run `grunt build` locally, but I have not been able to figure out how to revise this pull request since I did not run that prior to opening this pr. Could you please walk me through how I can correct this? I'm still a Git newbie and would really appreciate it. Thank you!

**Review by TildaDares — APPROVED** [review]
You were able to figure it out @Innominata88. Great work!

**Comment by TildaDares** [comment]
@Innominata88 Can you remove the `package-lock.json` file from this PR? You can do that by copying the [package-lock.json](https://github.com/publiclab/PublicLab.Editor/blob/main/package-lock.json) file contents from this repo and pasting it in your own local file. Then commit and push. Thanks!

**Comment by Innominata88** [comment]
@TildaDares I am so sorry I just saw your message. I had not had a chance to get on here and I must have missed the email notification. I have updated the file as you requested and will check back to ensure this worked.

Again, I really appreciate your patience and the time you have taken explaining everything to me and apologize for the delay.

**Comment by TildaDares** [comment]
Hi @Innominata88, that's fine. I think the `package-lock.json` has been removed.

**Comment by TildaDares** [comment]
Great work @Innominata88!

**Pull request merged**
