### PR TITLE
Fixes for table template

### LINKED ISSUE #309: Table template maker seems broken
**Please note we are preparing to participate in Google Code-in, and have reserved this issue for GCI participants - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Not a huge deal, but just documenting for future fixes -- looks like somehow our "table template generator" which was already imperfect, but kind of handy, has broken:

image

It used to show 2 inputs that you could put numbers into for your # of columns and rows, and it would generate a table. Code is here:

https://github.com/publiclab/PublicLab.Editor/blob/master/src/modules/PublicLab.RichTextModule.Table.js

If anyone got interested in fixing this, it'd be great! Thanks!

### PR DESCRIPTION
**Pull request by tsparksh**
Fixes #309 

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below
table

### CODE REVIEW

**Comment by tsparksh** [comment]
@publiclab/reviewers, what branch should I use for PR?

**Comment by gauravano** [comment]
hey @tsparksh, you should create a feature branch for the PR i.e., suppose you start working on a feature, then you can create a new branch from the master branch using git branch -b `branch-name`. 

This will allow you to work on multiple features at once, otherwise, you have to wait for the previous PR to be merged so that master becomes free for the new branch and so on.

**Comment by gauravano** [comment]
In this case, as it's refactoring so you can name your branch as `refactor/table-fix` maybe?

**Comment by tsparksh** [comment]
> In this case, as it's refactoring so you can name your branch as `refactor/table-fix` maybe?

I couldn’t change brach in this PR so i created a new one. 
Done in #364

**Pull request closed without merging**
