### PR TITLE
Compact Design for main Image Module

### LINKED ISSUE #592: More compact design for main image module
Hi all, I wanted to request a more compact design for this section, especially on narrower screens. See how the buttons could be side by side and a bit smaller?

image

The older design had fewer buttons but it was more compact, and I think we could get closer to that amount of space:

image

Who would like to try to take this up? I think it's primarily CSS. Thanks all! cc @publiclab/editor @sagarpreet-chadha

### PR DESCRIPTION
**Pull request by shreyaa-sharmaa**
# Fixes #592 

## **Tablet:**
Screenshot from 2020-08-13 02-48-24
Screenshot from 2020-08-13 02-47-19

## **Phone:**
mobile

## **Laptop:**
Screenshot from 2020-08-13 02-47-59
Screenshot from 2020-08-13 02-48-10

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by shreyaa-sharmaa** [comment]
Review please @jywarren @sagarpreet-chadha

**Comment by jywarren** [comment]
This looks really great, @shreyaa-sharmaa !!! I wonder if we can get the buttons to be side-by-side on mobile, what do you think? 

I also wonder, is it possible to have the "remove file" button only appear once there is an image? This maybe could also be done in CSS, i guess, or with `$('.button').hide()` maybe?

Thanks, this is great!!!

**Comment by shreyaa-sharmaa** [comment]
If we place the buttons side by side then where should we place the progress bar and filename? Above the buttons in both cases? 
I'll make the changes to `remove file` button.

**Comment by shreyaa-sharmaa** [comment]
Hides remove file button when not in use. Also hides the filename when file is removed.
GIF of the changes:
simplescreenrecorder-2020-08-14_03 39 30

**Comment by jywarren** [comment]
Awesome, and yes, that sounds great regarding the progress bar! Thanks so much!!!

**Comment by shreyaa-sharmaa** [comment]
Does this look okay @jywarren ?
Screenshot from 2020-08-14 04-10-34

**Comment by shreyaa-sharmaa** [comment]
Mobile:
mobile
Also noting the slight change in position of filename now:
Screenshot from 2020-08-14 04-18-25

**Comment by jywarren** [comment]
It looks tremendous. @shreyaa-sharmaa this is really excellent work. Merging now and releasing the next version!

**Comment by jywarren** [comment]
Hi @shreyaa-sharmaa - now that this is merged, can you be sure that the changes are also implemented in `plots2`'s matching templates? Thank you!!!

**Comment by jywarren** [comment]
Hi @shreyaa-sharmaa i'd love to publish this on `plots2` if you have any time today! I know it's probably late there. If not, we can push through a small new publication later in the week. Thanks so much for your help!

**Comment by shreyaa-sharmaa** [comment]
On it @jywarren!

**Comment by shreyaa-sharmaa** [comment]
Linking it here https://github.com/publiclab/plots2/pull/8327

**Pull request merged**
