### PR TITLE
UI Revamp

### PR DESCRIPTION
**Pull request by niravasher**
Acoording to issue #216 I have worked to make the new User Interface which is perfectly responsive on devices like laptop, phones and Ipad.
For doing so I made a new css file named localEdits.css inside the dist folder and have made modifications to examples/index.html and dist/publicLab.Editor.css and publicLab.Editor.js
I hope you like the new UI as I have made it almost exactly as descripted in the issue.

### CODE REVIEW

**Comment by rexagod** [comment]
Hey @niravasher! Can you change the title of this PR to something like `UI revamp` for better semantics? Thanks!

**Comment by niravasher** [comment]
I am very sorry for creating this merge conflict as well as for late reply. I have changed the title of the pull request as "UI revamp" @rexagod

**Comment by rexagod** [comment]
No worries @niravasher. Feel free to let us know if you get stuck anywhere. Thanks!

**Comment by jywarren** [comment]
Hello! We haven't seen any activity on this for a while, so we'll close it now. But if you're still interested, please feel free to re-open and pick the conversation back up! Thank you!! 🎉

**Pull request closed without merging**
