### PR TITLE
Add contrast theme for mobile chrome viewscreens

### PR DESCRIPTION
**Pull request by anto004**
[fix-issue 259](https://github.com/publiclab/PublicLab.Editor/issues/259)
Better theme contrast for mobile chrome viewscreens

### CODE REVIEW

**Comment by jywarren** [comment]
This looks really interesting! Could you share a screenshot of what it looks like? Thank you!

**Comment by anto004** [comment]
Hey Jeffrey,I've attached the screenshot with this email, let me know if you want me to make any changes.
    On Friday, February 15, 2019, 7:59:34 AM PST, Jeffrey Warren <notifications@github.com> wrote:  
 
 
This looks really interesting! Could you share a screenshot of what it looks like? Thank you!

**Comment by VladimirMikulic** [comment]
@jywarren @gauravano the PR is ready for merge :)

**Comment by jywarren** [comment]
Awesome! Yes, will merge shortly! Thanks!

**Comment by jywarren** [comment]
Just after https://github.com/publiclab/PublicLab.Editor/pull/362

**Comment by jywarren** [comment]
Thank you so much!

**Pull request merged**
