### PR TITLE
Main Image box CSS improved

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes: #450 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

editorimage

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @jywarren Have a look.
Thanks

**Comment by VladimirMikulic** [comment]
Personally, I would prefer a more gentle touch by increasing blur and decreasing opacity over the subtle dark "border". @nstjean what do you think?

**Comment by nstjean** [comment]
@VladimirMikulic Yes I agree. And maybe we should get rid of the rounded corners? Just because on the rest of the site we have square edges on the pictures.

**Comment by NitinBhasneria** [comment]
This is the change after the last commit.
Screenshot from 2020-06-02 14-56-21

**Comment by NitinBhasneria** [comment]
@VladimirMikulic Please review this.

**Comment by jywarren** [comment]
Hi! Thanks for all the input folks! The dotted line is supposed to indicate a "drop zone", which is a style you'll see around the web:

https://duckduckgo.com/?q=drop+zone+css&atb=v141-5&iax=images&ia=images



image

I think the rounded corners and dotted line both contribute to this look and are familiar to some folks! 

I'm definitely open to some refinements but those two elements seem to help a lot. Here's what it currently looks like:

image

Are there things we could do to make it look even more like a "drop zone"?

Thank you!!!

**Comment by NitinBhasneria** [comment]
@jywarren I agree with your point but when the image is uploaded this dotted looks wired.
We can convert the dotted to a normal solid on uploading. What are your views on this?

**Comment by jywarren** [comment]
Hi @NitinBhasneria! Generally that seems OK to me! But i wonder if we could look to a familiar model for this change in appearance in other projects' "drop zones" and cite them here? Thank you!

**Comment by emilyashley** [comment]
Dropping in this helpful diagram and vocabulary here~ 
10 usability heuristics

**Comment by NitinBhasneria** [comment]
@jywarren @emilyashley how about this.
howaboutthis

**Comment by jywarren** [comment]
That looks really nice!

**Comment by NitinBhasneria** [comment]
I will be implementing this then.👍

> That looks really nice!

I will be implementing this then.👍

**Comment by NitinBhasneria** [comment]
gigg
@jywarren which will be better for our editor. first or this?

**Comment by jywarren** [comment]
Hi! I think the background color change really helps in (1). So, i guess that one? I also like the padding around the dotted line! It helps make that line visible. Thanks!

**Comment by NitinBhasneria** [comment]
> Hi! I think the background color change really helps in (1). So, i guess that one? I also like the padding around the dotted line! It helps make that line visible. Thanks!

ok thanks @jywarren

**Comment by NitinBhasneria** [comment]
@jywarren I can't get this branch. Dunno why. Although I have made changes to this branch it guided me to open other PR #516 Have a look.
Closing this.

**Comment by jywarren** [comment]
Oh, i'm sorry, i think you pointed at the wrong PR in #516? Where did you move to? Thanks!

**Pull request closed without merging**
