### PR TITLE
fix toolbar stickness issue 

### LINKED ISSUE #394: Stickness of toolbar
Screenshot from 2020-02-01 20-17-37

Screenshot from 2020-02-01 20-36-03

As you can see the toolbar always remains sticked to the bottom. Is it a bug or intended behavior.
It's caused by this piece of code 
https://github.com/publiclab/PublicLab.Editor/blob/7aacb32e7bdb5e3aa72e3ba61311a7fbc442b759/src/modules/PublicLab.RichTextModule.js#L311-L335

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
fixes #394 
Toolbar now only floats when the scroll is on the editor text/body area, in both Rich and Markdown mode.

toolbar3

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
@jywarren @emilyashley @shreyaa-s @keshav234156 @NitinBhasneria 

i think i may need to also make the toolbar responsive on this PR, or do we need to open a different PR for that?

**Comment by Shulammite-Aso** [comment]
@emilyashley @jywarren @keshav234156 @NitinBhasneria @shreyaa-s please review.

**Comment by NitinBhasneria** [comment]
Great work @Shulammite-Aso. 
I just want to add that the toolbar sickness is not consistent as it is to be. When we scroll up the toolbar disappears and appears again(on further scrolling). 
**Expected Behaviour:** The toolbar should stick when we scroll up and it should disappear when toolbar comes to the top of the editor.
editortoolbar

**Comment by Shulammite-Aso** [comment]
Thanks @NitinBhasneria 
I was seeing similar behaviour until i added my last commit, i think it fixed it as i no longer see it, i don't know why can still observe it. Did you pull in my last commit? or maybe you should try reloading your browser.

**Comment by NitinBhasneria** [comment]
> Thanks @NitinBhasneria
> I was seeing similar behaviour until i added my last commit, i think it fixed it as i no longer see it, i don't know why can still observe it. Did you pull in my last commit? or maybe you should try reloading your browser.

Can you attach the gif of changes after the last commit?

**Comment by Shulammite-Aso** [comment]
Okay @NitinBhasneria i think i understand what you mean better now, the toolbar isn't beginning to float immediately it hits the footer..  I'll try to fix that.

**Comment by Shulammite-Aso** [comment]
Hi @NitinBhasneria this works fine now i guess, do check.


toolbar3

**Comment by emilyashley** [comment]
Awesome, thanks for this! I think it's fine to have it in two different PR's :)

**Comment by NitinBhasneria** [comment]
Awesome @Shulammite-Aso.

**Comment by shreyaa-s** [comment]
This looks good. Great work @Shulammite-Aso ! :smile:

**Comment by Shulammite-Aso** [comment]
@jywarren i think we can merge this, as it does solve the basic problem, which is making the toolbar accessible while not having it float outside the text area.  Other design options will be a matter of preference.  We can change it to suit other popular preference if there becomes need for it.

Thanks!!!

**Review by Sagarpreet — COMMENTED** [review]
The logic is so simple and clean 😄

**Pull request merged**
