### PR TITLE
Converted formatter jasmine file to jest test file fixes #774

### LINKED ISSUE #774: Create and port formatter jasmine file to jest test

### PR DESCRIPTION
**Pull request by NARUDESIGNS**
@jywarren I think this one passes just fine. 
Please review, thanks!

### CODE REVIEW

**Comment by jywarren** [comment]
Would you like to remove the corresponding test from Jasmine in the same PR?

**Comment by NARUDESIGNS** [comment]
> Would you like to remove the corresponding test from Jasmine in the same PR?

Alright.

**Comment by NARUDESIGNS** [comment]
@jywarren I need your help please, I'm not sure if this is the right thing to do but I'm unable to push after deleting the formatter jasmine file.

Screenshot 2022-01-04 at 21 56 02

**Comment by NARUDESIGNS** [comment]
Oh, I've been able to delete the `formatter_spec.js` file and now pushed changes. Please review again @jywarren

**Comment by jywarren** [comment]
I think the command would be 

> `git push origin formatter-jest-test-conversion`

to push to your own remote fork and the `formatter-jest-test-conversion` branch. If you did `main` it would try to push to your remote main branch. That'd be recoverable but you generally want your main branch to match the `publiclab` main branch, so you can do things like rebase on top of it. It's like saving a copy of the latest `publiclab` changes so you can do all your work in relation to it. Make sense?

**Comment by jywarren** [comment]
Looks super! We can start deleting all the test files we've migrated now!

**Pull request merged**
