### PR TITLE
refined custom insert dropdown UI fixes #816

### LINKED ISSUE #816: Add mouse pointer and background colors to the dropdown list in custom insert popover. Repeat for other popovers

### PR DESCRIPTION
**Pull request by NARUDESIGNS**
Refined the custom insert UI by:
* adding hover effect
* adding necessary padding and margin as well
* adding cursor pointer

Here's what it looks like currently

Screenshot 2022-01-31 at 3 37 37 PM

Here's what the fix looks like

Screenshot 2022-01-31 at 3 37 17 PM

@jywarren @TildaDares please have a look

### CODE REVIEW

**Review by TildaDares — APPROVED** [review]
Amazing work @NARUDESIGNS

**Review by govindgoel — APPROVED** [review]
LGTM!

**Review by jywarren — APPROVED** [review]
So nice. Thank you!!

**Comment by NARUDESIGNS** [comment]
Thank you too! 😊

**Pull request merged**
