### PR TITLE
Jest test for bold and italic command

### PR DESCRIPTION
**Pull request by shreyaa-sharmaa**
To be merged after #541 . Basic testing of bold and italic function in both modes.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
This looks great!!

i guess we'll have to add more tests cases as we fix bugs.

**Comment by jywarren** [comment]
Wow cool! The test failed -- actually a useful thing to see! 

```
> publiclab-editor@2.0.6 test-ui /home/travis/build/publiclab/PublicLab.Editor
> node ./node_modules/.bin/jest
 FAIL  test/ui-testing/italic.test.js
  Italic Text
    ✕ Adds emphasized text in rich text mode (71ms)
    ✕ Adds emphasized text in markdown mode (112ms)
  ● Italic Text › Adds emphasized text in rich text mode
    TypeError: PL.Util.enableRichTextModeKeyboardShortcut is not a function
      at HTMLDocument.<anonymous> (file:/home/travis/build/publiclab/PublicLab.Editor/dist/PublicLab.Editor.js:21548:11)
      at e (file:/home/travis/build/publiclab/PublicLab.Editor/node_modules/jquery/dist/jquery.min.js:2:30005)
      at t (file:/home/travis/build/publiclab/PublicLab.Editor/node_modules/jquery/dist/jquery.min.js:2:30307)
      at Suite.Object.<anonymous>.describe (test/ui-testing/italic.test.js:9:3)
  ● Italic Text › Adds emphasized text in markdown mode
    expect(received).toBe(expected) // Object.is equality
    Expected: true
    Received: false
```

https://travis-ci.org/github/publiclab/PublicLab.Editor/jobs/703594757#L293

🎉 🎉

**Comment by jywarren** [comment]
Great work getting this started. And thanks a ton for the review, @Shulammite-Aso !!!

**Comment by shreyaa-sharmaa** [comment]
@jywarren looked into why the tests were failing and it is because of this https://github.com/publiclab/PublicLab.Editor/issues/490#issuecomment-647360701 . As indicated here, 
Screenshot from 2020-06-30 23-12-22

Also Keshav has fixed this here https://github.com/publiclab/PublicLab.Editor/issues/490#issuecomment-648279527. Local test results after commenting out `PL.Util.enableRichTextModeKeyboardShortcut` 
Screenshot from 2020-06-30 23-09-25
whereas they failed if we left it as it is. I think the tests should work fine once we get the error fixed in main.

**Comment by jywarren** [comment]
OK, let's keep a lookout for that fix and then we can rebase this and mark this ready to merge? Thanks!

**Comment by keshav234156** [comment]
ok I will a seprate PR to fix and merge this test quickly

**Comment by shreyaa-sharmaa** [comment]
@keshav234156 I've fixed it here itself. Thanks for pointing it out in gsoc planning issue.

**Comment by shreyaa-sharmaa** [comment]
I've fixed the previous error and refined the tests as well but the build is failing. Italic and bold tests follow the exact same code, but the italic test works whereas the bold test fails. Everything works fine locally. Any idea what might be wrong?
Screenshot from 2020-07-03 17-21-12

**Comment by Shulammite-Aso** [comment]
Maybe you should rebase??

**Comment by shreyaa-sharmaa** [comment]
Already done.

**Comment by shreyaa-sharmaa** [comment]
Since I can't really figure out what is wrong, I'll be removing bold test from here and opening a new PR for it. So that we could fix the error and get started on the other tests after this PR.

**Comment by shreyaa-sharmaa** [comment]
Please review @jywarren @emilyashley @keshav234156 @NitinBhasneria @Shulammite-Aso . Thanks!

**Comment by keshav234156** [comment]
Restarting Travis!!

**Comment by keshav234156** [comment]
@shreyaa-sharmaa tests look good and are working well. Can you please document the tests( what each step of a test is doing) so that it becomes easy for the newcomer to understand and implement a similar test for the future.
Thanks!!

**Comment by shreyaa-sharmaa** [comment]
Done @keshav234156!!

**Comment by jywarren** [comment]
Awesome, folks!!! Great work!!!!

**Comment by jywarren** [comment]
Awesome work! This is tremendous!

**Pull request merged**
