### PR TITLE
Choose file button IMPROVED:

### PR DESCRIPTION
**Pull request by NitinBhasneria**
Fixes : #433 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

editor4

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by NitinBhasneria** [comment]
@VladimirMikulic @jywarren Have a look.
Thanks

**Comment by VladimirMikulic** [comment]
Does it display a filename once a file has been uploaded?

**Comment by NitinBhasneria** [comment]
No, do we have to display. As the image popup itself displays I don't think it is necessary.

**Comment by VladimirMikulic** [comment]
I think that it would be a nice UX.

**Comment by NitinBhasneria** [comment]
@jywarren @cesswairimu @sagarpreet-chadha @SidharthBansal Please have a look and guide further.

**Comment by NitinBhasneria** [comment]
@VladimirMikulic I am stuck with some problem and seen a new issue due to which this particular PR is of no use. I am opening an issue for the error. Please have a look. #455

**Comment by NitinBhasneria** [comment]
Currently closing this

**Pull request closed without merging**
