### PR TITLE
Refined User interface design of main image upload

### LINKED ISSUE #148: Refine user interface design of main image upload
When people are prompted to upload a main image, it looks like this: 

image

Then when they drag in an image, it looks like this:

image

It can be confusing because you see only part of the image. 

Instead, let's change it to show the whole thumbnail, like this:

screen shot 2018-07-06 at 6 27 45 pm

The code which displays the image once it's uploaded is here: 

https://github.com/publiclab/PublicLab.Editor/blob/e4fcc6b769f3ad81364237924def5bc97db4f015/src/modules/PublicLab.MainImageModule.js#L109

We can use jQuery to display it differently!

### PR DESCRIPTION
**Pull request by DivyeshPuri**
Fixes #148 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by DivyeshPuri** [comment]
@publiclab/reviewers Can you please review this PR.

**Comment by jywarren** [comment]
This is great. If you bump the version number in `package.json` by an `0.0.x` version number, this'll get published onto PublicLab.org soon!

**Comment by jywarren** [comment]
sorry - if you look at the version number at the top of the package.json
file, it might be 1.1.3, for example. To bump up the version, by a minimum
amount, you could change it from 1.1.3 to 1.1.4 -- or whatever the
equivalent is for the current version. If you could add that to this PR, we
would love to release a new version based on your contributions!

**Comment by DivyeshPuri** [comment]
@jywarren Thank you for explaining.

**Comment by jywarren** [comment]
Hi -- this looks perfect; merging now. 👍 🎉  If you're looking for a new challenge, please take a look at https://code.publiclab.org#r=all; we prefer to leave `first-timers-only` issues for complete newcomers, but there are plenty of others we need help with! Thanks!

**Pull request merged**
