### PR TITLE
Detect data urls and display an alert

### LINKED ISSUE #175: Detect data-urls in content, and display a warning
Just like in this PR, we could scan the content for data urls, and show a notice that says this may cause issues on upload: https://github.com/publiclab/PublicLab.Editor/pull/130

The key section to look at as an example is:

https://github.com/publiclab/PublicLab.Editor/blob/5b83622d5ca730901ebdde6fc0097be322a3e9e7/src/modules/PublicLab.RichTextModule.js#L153-L159

Instead of the string above, we'd search for the data-url, which always starts with something like: `data:image/jpeg;base64,`

We could search for just `data:image/` and that would probably work.

In the message, we could say to "click here" with a link to open the image in a new window, and direct the user to `Save it to your desktop, then re-upload it.` 

This is an annoying issue, but it can  badly overload our database when it's saved as a string into a text record instead of uploaded separately. (see related https://github.com/bevacqua/woofmark/issues/69 upstream)

A follow-up could be to actually do the upload automatically on detection, but let's start with just detecting it! Any help appreciated!

### PR DESCRIPTION
**Pull request by okonek**
fixes #175
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!
data-urls

### CODE REVIEW

**Comment by okonek** [comment]
@jywarren Take a look and review when you have time, please.

**Comment by jywarren** [comment]
Hi, i'm sorry, i merged a commit by @dependabot and caused a conflict. Do you think you could resolve it?

I'm also wondering if we could add a test for this behavior. We could paste a small dataurl into the codebase and then check for the alert to be shown. We could do something pretty simple -- see this for entering something into the rich text module textarea:

https://github.com/publiclab/PublicLab.Editor/blob/19a379062304fabc6e280f4915a5f5a889c2595b/spec/javascripts/rich_text_module_spec.js#L36

then we could do `expect($('.alert.data-urls-warning').length).toBe(1);`

What do you think?

**Comment by jywarren** [comment]
But also I believe we need to run `grunt build` on this and to check in the newly compiled file from the `dist` folder.

**Comment by jywarren** [comment]
Thanks @okonek ! This project is a bit neglected so your help here is MUCH appreciated! Several of the other sub-libraries of PL have a lead developer, but not this one! It's too bad because there are some really cool features which we could build out, like this one on autocompleting tagnames, usernames, and such with the `atwho` library, just as we do in comments on PublicLab.org: https://github.com/publiclab/PublicLab.Editor/issues/44

**Comment by okonek** [comment]
@jywarren No, problem I can write the tests, but how am I supposed to resolve the conflict? Should I rebase or just remove this fork and  start another one? What did you mean by that? Thanks.

**Comment by okonek** [comment]
@jywarren I'm very sorry, but I was sitting on this for like two or three hours and couldn't figure out the way to do the tests for this, because setting the textarea value with code doesn't trigger the `keydown` event. Could you approve it how it is, please? Maybe we could figure out how to do the tests later on.

**Comment by jywarren** [comment]
Approved! I think there's a way to trigger the event manually... Maybe we do this elsewhere in the tests?

**Comment by okonek** [comment]
Yes, I tried $().trigger("keydown"), but it did not succeed, also I searched in the other tests for some similar code, but I did not find any.

**Pull request merged**
