### PR TITLE
Attempt to solve issue #88

### PR DESCRIPTION
**Pull request by djmgit**
#85

### CODE REVIEW

**Comment by djmgit** [comment]
@jywarren I have added a new module PublicLab.RichTextModule.CodeFences.js and initialized it in /src/adapter/PublicLab.Woofmark.js .

**Comment by jywarren** [comment]
Great, does it work? It passes tests!

**Comment by djmgit** [comment]
@jywarren I have initialised the module in PublicLab.Woofmark.js  as it was mentioned in the issue (comments). The button is getting added but on clicking it the desired action is not happening, that is ``` is not getting inserted

**Comment by jywarren** [comment]
Can you try inserting `console.log('test')` into various places to confirm
that it is actually executing the code you've entered? Also, can you attach
a screenshot of the button? Thank you, this is very exciting!

**Comment by jywarren** [comment]
So i had a chance to look, and the error is in `initCodeFences` -- module is not defined. I think you need `_module` instead -- then hopefully it'll work!

Also, it's probably a good time to add a test, so you can confirm that it works. Remember [this example](https://github.com/publiclab/PublicLab.Editor/blob/master/spec/javascripts/tags_module_spec.js) -- you can just start with a test that an element with `.woofmark-command-code-fences` exists?

And maybe choose an appropriate icon from fontawesome.io (i like that part, myself)

**Comment by djmgit** [comment]
@jywarren found my mistake, now the button is functioning
On clicking the button however two code areas are getting added. (screen shot below)
I am adding tests.

**Comment by djmgit** [comment]
aa

**Comment by djmgit** [comment]
currently icons are not getting displayed, I am trying to find out why.

**Comment by jywarren** [comment]
ah, i think the icons use an absolute path, so you can probably ignore them
for now -- just choose the one you want and upload a commit to test!

Thanks! did you figure out the double code fence thing?

**Comment by djmgit** [comment]
@jywarren I am trying to find out the double fencing part. When ever  a single ``` is being inserted another ``` is getting inserted automatically. I have used console.log to verify that chunks.before is giving all the html before the cursor and chunk.after is giving all the html after the cursor,so technically there should only be two ``` inserted, however 4 ``` is getting inserted.

**Comment by jywarren** [comment]
Can you confirm that the whole system is being initialized only once? For
example, what if you console.log('click') in the click event handler, and
see if somehow it's been tied to the handler twice? Let's find where the
doubling up is happening!

**Comment by jywarren** [comment]
Oh no! I just looked at this again, and I realized there is already a button to add code blocks; it's the fourth one from the left!

However, I see a strong need for this code still -- the very similar request here: https://github.com/publiclab/PublicLab.Editor/issues/88

for a `<hr />` horizontal rule, which in markdown is `****`.

It's also a little easier because it only needs to be added once, not with open AND closing additions, like code fences. 

So -- many apologies for not catching this earlier, but do you think you could rename your new module `PublicLab.RichTextModule.HorizontalRule.js` ? and change the two fences for a single `****`?

Thank you!

**Comment by jywarren** [comment]
Hi, @djmgit - I refactored this to do horizontal rules -- it was pretty simple -- and rebased it. I think it's ready to merge, so let's see how the tests do!

**Comment by jywarren** [comment]
This worked perfectly -- bumping the version and merging.

**Comment by jywarren** [comment]
Thank you for writing this! It was cleanly implemented and the final changes were pretty simple.

**Pull request merged**
