### PR TITLE
poorly wrapping Markdown button on narrower screens on /post

### PR DESCRIPTION
**Pull request by Sagarpreet**
Before:

Screenshot 2020-10-13 at 1 34 24 PM
Screenshot 2020-10-13 at 1 33 32 PM

After: 
Screenshot 2020-10-13 at 1 30 53 PM

Screenshot 2020-10-13 at 12 58 53 PM

### CODE REVIEW

**Comment by Sagarpreet** [comment]
Fixes 2 things:

1. "Enter the content here" placeholder was out of box.
2. Editor Buttons on smaller screen were not wrapping properly

**Comment by Sagarpreet** [comment]
@jywarren kindly review this

**Comment by jywarren** [comment]
Trying to get GitPod to run successfully, it had stalled!

**Review by jywarren — APPROVED** [review]

**Comment by jywarren** [comment]
Ah, i think this now needs a conflict resolved. Thanks @Sagarpreet !!!

**Comment by Sagarpreet** [comment]
Done @jywarren 👍

**Comment by jywarren** [comment]
Awesome! Thanks!!!

**Pull request merged**
