### PR TITLE
Improve extras section

### LINKED ISSUE #157: Improve extras section
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
https://publiclab.github.io/PublicLab.Editor/examples/ in here is extras section at the bottom but it's not looking good for short resolution window and
extras

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 

make mobile repsonsive extras section, using Bootstrap to hide the button text but not the icon (only at lower screen widths!)

Code links….
https://github.com/publiclab/PublicLab.Editor/blob/e4fcc6b769f3ad81364237924def5bc97db4f015/examples/index.html#L171

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

### PR DESCRIPTION
**Pull request by thesparks**
Fixes #157  

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

### CODE REVIEW

**Comment by thesparks** [comment]
@avsingh999 please review

**Comment by shivani-kapania** [comment]
@thesparks can you share screenshots?

**Comment by Rishabh570** [comment]
@thesparks Please provide a working GIF showing the change (you can use `peek` for that) or a couple of screenshots before, after and at _550px_ would suffice, whichever way you like it...

**Comment by thesparks** [comment]
deepin-screen-recorder_select area_20181024204944

**Comment by shivani-kapania** [comment]
@thesparks good work! 👍

**Comment by thesparks** [comment]
@shivani-kapania, please confirm my GCI task

**Comment by jywarren** [comment]
Great!!!

**Pull request merged**
