### PR TITLE
Revert "Bump woofmark from `12e2c1d` to `39237b7`"

### PR DESCRIPTION
**Pull request by keshav234156**
Reverts publiclab/PublicLab.Editor#597

### CODE REVIEW

**Comment by jywarren** [comment]
Hi @keshav234156 can you explain this a little more? Thank you!

**Comment by keshav234156** [comment]
@jywarren tests were failing #597 https://travis-ci.com/github/publiclab/PublicLab.Editor/jobs/372642656#L255
So that why created a revert PR

**Comment by jywarren** [comment]
Yes, however, can you explain why they were failing? And, given that those are updates we really want from `woofmark`, and they passed tests originally before I merged that, what do you think we should do next? Thank you so much, Keshav!

**Comment by sagarpreet-chadha** [comment]
Hey @keshav234156 , the tests in other PR's should also fail, right?
But they seem to be passing in https://github.com/publiclab/PublicLab.Editor/pull/600

**Comment by jywarren** [comment]
I think I'll close this as #600 indeed seems to show this is not an issue! Thank you!!

**Comment by keshav234156** [comment]
> I think I'll close this as #600 indeed seems to show this is not an issue! Thank you!!
I don't think think so. Errors can be seen here as well https://travis-ci.com/github/publiclab/PublicLab.Editor/jobs/379516209. #600 migh not have been rebased that why it's not showing errors. I was not able to find the reason but it is due to this PR.

**Comment by jywarren** [comment]
Oh, i see - ok, we need to document this carefully. @keshav234156 moving to https://github.com/publiclab/PublicLab.Editor/issues/607 cc @sagarpreet-chadha

**Pull request closed without merging**
