### PR TITLE
Added gitpod config

### LINKED ISSUE #475: Auto-generate testable demos from all pull requests with GitPod.io
To make testing out new PRs faster and easier, we could integrate with GitPod.io, which auto-builds and hosts a browser-based version. I think, though i'm not sure, that we could do this with IS:

https://www.gitpod.io/

This could make debugging much easier too!

### PR DESCRIPTION
**Pull request by svenefftinge**
Hi, I was pointed to your project and saw you were looking into adding gitpod support.
So here it is. I configured it so that it starts two terminals at start. The right one starts the live-server process and the left one is there to re-run the build (history up to get `npm run build`).
It also opens the preview on the examples directory at start.

You can test it on my fork, by clicking this link:
https://gitpod.io/#https://github.com/svenefftinge/PublicLab.Editor

Fixes #475

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
Oh!  Thanks for this.

I didn't know you'll be making a PR. 

Hopefully the team here will take a look at this soon.

**Comment by svenefftinge** [comment]
> I didn't know you'll be making a PR.

It was just the easiest way to share the config.
Please, feel free to do anything you like with this.

**Comment by cesswairimu** [comment]
This is great thanks @svenefftinge  for opening this :tada: 

pinging @jywarren and @emilyashley  to take a look

**Comment by cesswairimu** [comment]
Just tested on your repo :tada: :tada: :tada: 

Peek 2020-06-17 17-28

**Comment by jywarren** [comment]
Oh darn! This exists! I must've missed it and then it got closed somehow... I'm not sure how. Reopening/repointing!

**Comment by jywarren** [comment]
Darn, i can't seem to repoint it. I wonder if something went wrong with the new GitHub PR repointing system. Let's coordinate in https://github.com/publiclab/PublicLab.Editor/issues/475 and open a new PR with the same changes? Note that our default branch is `main` now. Thank you!

**Comment by jywarren** [comment]
OK, moving to #553! Thank you all!

**Comment by jywarren** [comment]
OK, i had to make my own branch to rebase... i hope this works! It uses the same commits, though, thank you! https://github.com/publiclab/PublicLab.Editor/pull/558

**Comment by jywarren** [comment]
Hi! Got this rebased, added some Github directives, and it passed! Merged, and many thanks! https://github.com/publiclab/PublicLab.Editor/pull/558

**Pull request closed without merging**
