### PR TITLE
Just added the requested task

### PR DESCRIPTION
**Pull request by namanrai**
Just created a pull request to add the code of conduct in the readme file.
This is for GCI and is my first task for this year.

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by namanrai** [comment]
@publiclab/reviewers Please help me with this task if something is missing

**Comment by namanrai** [comment]
fixes #0000

**Comment by debck** [comment]
This PR is the duplicate of https://github.com/publiclab/PublicLab.Editor/pull/361 . 
So closing this. 
Also, @fluctix  you should run the made changes in a PR locally and then approve the changes.
Look at the review made in the other PR. You can understand where you went wrong.

**Comment by fluctix** [comment]
Ahh I get it, thank you for the feedback , will keep that in mind next time.

**Pull request closed without merging**
