### PR TITLE
Update to Bootstrap 4

### LINKED ISSUE #508: Updating to Bootstrap 4
PublicLab.Editor uses Bootstrap 3 and PublicLab.org uses Bootstrap 4. There is a considerable amount of difference between the both versions of Bootstrap that lead to inconsistencies. So we should update PublicLab.Editor to version 4

### PR DESCRIPTION
**Pull request by keshav234156**
Fix #508 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
@jywarren @NitinBhasneria @shreyaa-s @Shulammite-Aso Please Review!!

**Comment by govindgoel** [comment]
The tests are failing due to some issues in bold.test.js

**Comment by shreyaa-sharmaa** [comment]
I pulled your branch and the tests worked fine locally, anyone knows why this might be happening then?
Screenshot from 2020-07-14 18-51-11

**Comment by shreyaa-sharmaa** [comment]
@keshav234156 do you mind if I make a testing commit in this branch?

**Comment by shreyaa-sharmaa** [comment]
@NitinBhasneria were you able to run the ui-tests in gitpod? It's throwing an error when I tried.

**Comment by keshav234156** [comment]
@shreyaa-s Yeah sure
For me as well tests are running locally well.

**Comment by keshav234156** [comment]
Even failing on https://travis-ci.com/github/publiclab/PublicLab.Editor/jobs/358505116

**Comment by shreyaa-sharmaa** [comment]
That didn't work. The exact same code works for italic here but fails for bold. The last time I faced this the only difference b/w the two codes was an additional line and adding it worked.
Also, the italic and bold, both tests, failed for `custom insert module` test. This is strange. I'll try to analyse the behaviour of the tests again and if it persists we can try shifting them to woofmark? 
Looping in @jywarren @Shulammite-Aso @NitinBhasneria , what do you all think?

**Comment by shreyaa-sharmaa** [comment]
Sorry to go overboard on the testing, but on a slightly better note, one of the two previously failing bold tests is now passing. 
The second test has passed, but the first one still fails. Restarting Travis.

**Comment by shreyaa-sharmaa** [comment]
Opened another pr for fixing this but all the tests passed there. I'll remove my commits from here.

**Comment by shreyaa-sharmaa** [comment]
These tests passed for mine, Nitin's, Shulammite's PRs as well your recent PR on listing. Try rebasing this as Nitin suggested in https://github.com/publiclab/PublicLab.Editor/pull/559#pullrequestreview-447153409, resolve conflicts and push the changes. That might work.

**Comment by NitinBhasneria** [comment]
> @NitinBhasneria were you able to run the ui-tests in gitpod? It's throwing an error when I tried.

same here.. bower process error

**Comment by shreyaa-sharmaa** [comment]
@keshav234156 can I open #559 for testing purpose or do you have any plans for it?

**Comment by keshav234156** [comment]
@shreyaa-s For me as well test are passing locally 
Screenshot from 2020-07-16 21-40-36

**Pull request closed without merging**
