### PR TITLE
Hiding Custom Insert Popover on Pressing `esc` button

### LINKED ISSUE #819: Hide Popover on pressing `ESC` button
The popover can be hidden on pressing `esc` button, this feature is not there right now so this feature can be added for better UI.

### PR DESCRIPTION
**Pull request by RaviAnand111**
fixes #819 

The custom insert popover will disappear on pressing `esc` button while popover is open.

hey @NARUDESIGNS @TildaDares , can you please have a look at this pr
Thank You

### CODE REVIEW

**Comment by NARUDESIGNS** [comment]
@RaviAnand111 nice one!
I have a question, did you place the code `woofmark-command` click method?
Remember we only want to listen to these events after the `custom-insert` or `table` button has been clicked.

**Comment by RaviAnand111** [comment]
> 

Yeah, totally forgot that part, I will do that and make a PR
Thanks

**Comment by RaviAnand111** [comment]
https://user-images.githubusercontent.com/59113935/152305630-def145bd-d645-4e67-9f15-3fe7c99a571e.mp4


Here is the video of how the code is working, 
Thanks

**Review by TildaDares — APPROVED** [review]
Great work @RaviAnand111

**Comment by jywarren** [comment]
Merged this too! Congrats!!!

**Pull request merged**
