### PR TITLE
Added background to tool buttons to prevent button transparency fixes #753

### LINKED ISSUE #753: Buttons has no background which makes it possible to see text behind it.
When the page is scrolled to a particular threshold, the tool buttons sticks to the page, allowing other contents to scroll under them. However, the tag, table, horizontal line, center and youtube buttons all have no backgrounds which make it possible to see the text which they overlap.
I expect those buttons to have a background and maybe match other button styles like the bold, italics, blockquotes etc...

Here's what it looks like presently

Screenshot 2021-10-24 at 06 18 34

### PR DESCRIPTION
**Pull request by RaviAnand111**
fixes #753
Changed btn-outline-secondary to btn-light with text formatter disabled and it is working fine.

### CODE REVIEW

**Comment by RaviAnand111** [comment]
@NARUDESIGNS , I forked and cloned again as I was unable to get to the previous version. So can you now review the pr. 
ThankYou

**Comment by NARUDESIGNS** [comment]
I totally get you. I made the same mistake when I first contributed as well. My formatter (prettier) added too many changes and I used `git revert <commit>` to revert to an earlier commit and then made it right.
However I was going to ask, you removed "btn btn-outline-secondary" and added "btn btn-light", did this solve the problem?
Can you please share a screenshot or a shot video for us to see how those buttons look after you added your changes?
@RaviAnand111 
cc @TildaDares

**Comment by RaviAnand111** [comment]
https://user-images.githubusercontent.com/59113935/147045224-b83afa23-bc77-4385-ba26-ea4213ed85cd.mp4

Here I have uploaded the video, you can check

**Comment by RaviAnand111** [comment]
@NARUDESIGNS

**Comment by NARUDESIGNS** [comment]
@RaviAnand111 awesome, well done and thanks!
Please also rename the PR to be more descriptive about the issue it is fixing and make sure to include "fixes issue #753"
For example, maybe - "Added background to tool buttons to prevent button transparency fixes #753"
cc @TildaDares

**Comment by RaviAnand111** [comment]
ThankYou @NARUDESIGNS, I have renamed the PR, you can see.

**Comment by NARUDESIGNS** [comment]
Awesome! @RaviAnand111 
@TildaDares do you want to have a final look, please?

**Review by TildaDares — APPROVED** [review]
Great job everyone! Looks good to me🎉

**Comment by RaviAnand111** [comment]
ThankYou for approving, @TildaDares , I am new to open source and it's working. Can you please tell me what is 1 workflow awaiting approval and merging is blocked and is there any problem with merging this Pull Request?

**Comment by TildaDares** [comment]
Hi @RaviAnand111, usually when a new contributor opens a PR, a maintainer has to approve and then run the tests. I just did that so the `1 workflow awaiting approval` text should be gone now.

Only users with push access to this repo can merge pull requests. You don't have to worry about the merging. You've done a great job!

**Comment by RaviAnand111** [comment]
Thanks, alot @TildaDares for explaining, I learned a lot of things about open source from this contribution and wish to learn more. I will keep contributing. ThankYou

**Comment by RaviAnand111** [comment]
Hey @TildaDares @NARUDESIGNS , I just saw that PR run was failed, base-tests were not successful, Can you please tell me whats happening and what should I do to make it right. 
ThankYou

**Comment by TildaDares** [comment]
Hi @RaviAnand111, those tests aren’t working for now. @NARUDESIGNS is currently working on converting them from jasmine to jest.

**Comment by jywarren** [comment]
This looks great. Thanks everyone!!!!!

**Comment by RaviAnand111** [comment]
yeah, my twitter handle is - 
ravi_anand_dev

**Pull request merged**
