### PR TITLE
Add eslint, lint-staged and Husky

### PR DESCRIPTION
**Pull request by keshav234156**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by keshav234156** [comment]
Previous similar PR but with merge conflicts 
https://github.com/publiclab/PublicLab.Editor/pull/519

**Comment by keshav234156** [comment]
It passed now!.
Earlier error was occurring as we can't replace all double quotes " " with single quote ' '

**Comment by jywarren** [comment]
Hi @keshav234156 ! Awesome. Can you try force-pushing `git push -f origin add-esli` (i think) this to the original PR so the conversation is preserved and linked clearly? Thank you!

**Comment by keshav234156** [comment]
I  can't force push as everything is upto-date. The branch of the previous PR was add-eslint. I made a new branch as there were many merge conflicts that weren't possible to fix including in package-lock.json and dist folder. So I made a new branch

**Comment by jywarren** [comment]
Ah, ok, i get it! But maybe you can do `git push -f origin HEAD:add-eslint`? I think that should work!

**Comment by keshav234156** [comment]
done!! It was totally a new thing to me. Thanks!! #519

**Comment by jywarren** [comment]
😄 Great! Moving back to #519 then!

**Pull request closed without merging**
