### PR TITLE
Add support for class attribute in links

### LINKED ISSUE #512: Some styled/custom HTML gets destroyed when converted to Markdown
When we create links with button styles, like this:

```html
<a class="btn btn-primary" href="https://publiclab.org">Test button</a>
```

and insert them into the editor in markdown mode, they'll appear as buttons following Bootstrap classes: http://getbootstrap.com/

But if we switch to Rich text mode, that gets converted to:

`[Test button](https://publiclab.org)`

And the styles are lost. Perhaps we should try to detect if classes exist and not disturb them? This might require a change to the upstream `woofmark` editor module. What do you think?

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
Fixes #512 

linkBtn

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] PR body includes `fixes #0000`-style reference to original issue #
* [ ] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
@jywarren wondering why this check is not completed yet,  is it normal?
Been this way for a week or more 🤔 with some of the other PR's too as I can see.

**Comment by shreyaa-sharmaa** [comment]
Try rebasing it?

**Comment by Shulammite-Aso** [comment]
> Try rebasing it?

will do this now

**Comment by jywarren** [comment]
Great! 🎉 🎉

**Pull request merged**
