### PR TITLE
fixed preview function

### PR DESCRIPTION
**Pull request by niravasher**
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `grunt jasmine`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] PR body includes `fixes #0000`-style reference to original issue #
* [x] ask `@publiclab/reviewers` for help, in a comment below

> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software

We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. 

Thanks!

### CODE REVIEW

**Comment by niravasher** [comment]
Fixed some previous work. Similar to #296 @VladimirMikulic 
Screenshot from 2020-02-17 15-24-24
Screenshot from 2020-02-17 15-24-55

**Comment by VladimirMikulic** [comment]
Which issue you were fixing with this?

**Comment by niravasher** [comment]
https://github.com/publiclab/PublicLab.Editor/issues/286 this one @VladimirMikulic

**Comment by VladimirMikulic** [comment]
Alright, but we already have a "preview" button.

**Comment by niravasher** [comment]
We have a publish button not a preview button @VladimirMikulic

**Comment by VladimirMikulic** [comment]
Well, the "Rich mode" button shows preview :)

**Comment by niravasher** [comment]
Not exactly though. Rich mode is like README on git. Jeff gave me the permission to work on it. @VladimirMikulic

**Comment by VladimirMikulic** [comment]
I am not preventing you from working, just checking if it's necessary. Feel free to work on this.

**Comment by niravasher** [comment]
Review this PR please. Also open new issues in this repo. Also there is no functionality in the extras tab. I have opened up an issue regarding the same, guide me what needs to be done there

**Comment by niravasher** [comment]
What happens when you click on this preview button? 

> Screenshot_20200218_102217
> 
> The "Preview" button is not responsive. It is overlapping with the "Publish" button.

**Comment by VladimirMikulic** [comment]
It shows preview that I can't get out of.

**Comment by niravasher** [comment]
Yes, I designed this preview button. Previously there were some issues with this remaining. In this PR, most of them are fixed. New elements like Image selected by the user can be inserted inside this preview menu

**Comment by niravasher** [comment]
> Screenshot from 2020-02-17 15-24-24
> Screenshot from 2020-02-17 15-24-55
Clicking on preview button shows this tab

**Comment by VladimirMikulic** [comment]
Not on my side.

Screenshot_20200218_124808


You should fix the issues with responsivness.

**Comment by vaibhavmatta** [comment]
Hey @niravasher !
Happy to see you contributing with enthusiasm. Please make the changes requested by @VladimirMikulic and update your pull request. Do tag me up when you are done with the changes, I ll review your PR and pass it if possible. 
Feel free to tag me up wherever you feel stuck. 
Thanks! 😊

**Comment by niravasher** [comment]
Shifted to #408 because I deleted my branch bymistake, retrieved work using git reflog. Sorry for the mistake.

**Comment by VladimirMikulic** [comment]
@niravasher alright, then I am closing this. Moved to #408.

**Pull request closed without merging**
