### PR TITLE
 Padding added to table popover button for editor fixes#752

### PR DESCRIPTION
**Pull request by RaviAnand111**
fixes#752

Hey, @NARUDESIGNS @TildaDares can you review the PR please ?

### CODE REVIEW

**Comment by NARUDESIGNS** [comment]
For your last 2 commits, I still see your formatter added lots of changes. @RaviAnand111

**Comment by RaviAnand111** [comment]
Sorry about that, I will rectify it ASAP.

**Comment by RaviAnand111** [comment]
Can you check it now please

**Comment by TildaDares** [comment]
Hi @RaviAnand111, the changes made by your formatter are still there. You can also check it yourself by clicking on the `Files changed` tab on this PR page. It shows a list of all the changes you made to each file. Thanks!

**Comment by TildaDares** [comment]
@RaviAnand111 Since the change you added is a one-liner, you can replace the contents of your local file with the contents of the remote Public Lab repo and then add your changes again.

**Comment by TildaDares** [comment]
Hi @RaviAnand111, have you disabled your linter/formatter?

**Comment by TildaDares** [comment]
@RaviAnand111 What IDE/text editor do you use?

**Comment by RaviAnand111** [comment]
VS code 
I had prettier enabled, but I disabled it.
I also disabled format on save setting

**Pull request closed without merging**
